### ISSUE TITLE
decorator seems to be broken with py.test

### ISSUE THREAD

**Issue by dmcclory** [spulec/moto#436] opened 2015-10-08 20:46 UTC
We've been using moto, but recently some of the tests seem to be broken. I tried using the example from the readme with py.test, and it fails. This is the same kind of error message we've been seeing in our suite. Is there something we're doing wrong? Everything looks ok.

```
import boto
from moto import mock_s3

@mock_s3
def test_my_model_save():
    conn = boto.connect_s3()
    conn.create_bucket('mybucket')

    model_instance = MyModel('steve', 'is awesome')
    model_instance.save()

    assert conn.get_bucket('mybucket').get_key('steve').get_contents_as_string() == 'is awesome'
```

```
>               response.status, response.reason, body)
E           S3ResponseError: S3ResponseError: 404 Not Found
E           <?xml version="1.0" encoding="UTF-8"?>
E             <Response>
E               <Errors>
E                 <Error>
E                   <Code>NoSuchBucket</Code>
E                   <Message>The specified bucket does not exist</Message>
E                   <BucketName>None</BucketName>
E                 </Error>
E               </Errors>
E             <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
E           </Response>

env/lib/python2.7/site-packages/boto/s3/connection.py:621: S3ResponseError
```

**Comment by hltbra** [comment] 2015-10-09 17:57
I cannot reproduce it. I just created a brand new virtualenv and tried this with pytest, but everything worked. Can you provide more details? Maybe you are using a library that is messing with http requests (like HTTPretty)?

My code:
```python
import boto
from boto.s3.key import Key
from moto import mock_s3

class MyModel(object):
    def __init__(self, name, value):
        self.name = name
        self.value = value

    def save(self):
        conn = boto.connect_s3()
        bucket = conn.get_bucket('mybucket')
        k = Key(bucket)
        k.key = self.name
        k.set_contents_from_string(self.value)


@mock_s3
def test_my_model_save():
    conn = boto.connect_s3()
    conn.create_bucket('mybucket')

    model_instance = MyModel('steve', 'is awesome')
    model_instance.save()

    assert conn.get_bucket('mybucket').get_key('steve').get_contents_as_string() == 'is awesome'
```

```shell
$ py.test -v test_gh_issue.py
=================================================================== test session starts ====================================================================
platform darwin -- Python 2.7.6, pytest-2.8.2, py-1.4.30, pluggy-0.3.1 -- /Users/hugo/.virtualenvs/tmp-7c424d7ca93ea422/bin/python
cachedir: .cache
rootdir: /Users/hugo/.virtualenvs/tmp-7c424d7ca93ea422, inifile:
collected 1 items

test_gh_issue.py::test_my_model_save PASSED
```

**Comment by dmcclory** [comment] 2015-10-09 18:13
I'm not using any special library & I too am working from a barebones virtualenv. Using the example you gave, it crashes at a call to `boto.create_bucket`:

```
virtualenv env
source env/bin/activate
pip install boto
pip install moto
pip install pytest
```

```
py.test foo.py 
========================================== test session starts ==========================================
platform darwin -- Python 2.7.5, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /private/tmp/what, inifile: 
collected 1 items 

foo.py F

=============================================== FAILURES ================================================
__________________________________________ test_my_model_save ___________________________________________

    @mock_s3
    def test_my_model_save():
        conn = boto.connect_s3()
>       conn.create_bucket('mybucket')

foo.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = S3Connection:s3.amazonaws.com, bucket_name = 'mybucket', headers = None, location = ''
policy = None

!! I've taken the liberty of excising most of the source of boto.create_bucket, but pytest prints it all out.

        else:
            raise self.provider.storage_response_error(
>               response.status, response.reason, body)
E           S3ResponseError: S3ResponseError: 404 Not Found
E           <?xml version="1.0" encoding="UTF-8"?>
E             <Response>
E               <Errors>
E                 <Error>
E                   <Code>NoSuchBucket</Code>
E                   <Message>The specified bucket does not exist</Message>
E                   <BucketName>None</BucketName>
E                 </Error>
E               </Errors>
E             <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
E           </Response>

env/lib/python2.7/site-packages/boto/s3/connection.py:621: S3ResponseError
======================================= 1 failed in 0.52 seconds ========================================
```

**Comment by dmcclory** [comment] 2015-10-09 18:17
and I tried updating my virtualenv, on the off chance that the was the problem. However, it still fails.

```
py.test foo.py 
========================================== test session starts ==========================================
platform darwin -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /private/tmp/cool, inifile: 
collected 1 items 

foo.py F
```

**Comment by hltbra** [comment] 2015-10-09 19:20
What moto version are you running? I tried it with latest (0.4.15).

Could you please copy and paste here the output or `pip freeze`? I would like to check at least `moto` and `httpretty` versions.

**Comment by dmcclory** [comment] 2015-10-09 19:27
Thanks for looking into this. (I didn't realize we were using httpretty at all). Pip freeze output:

```
(env)$ pip freeze
boto==2.38.0
Flask==0.10.1
httpretty==0.8.10
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
moto==0.4.15
py==1.4.30
pytest==2.8.2
requests==2.8.0
six==1.10.0
Werkzeug==0.10.4
wheel==0.24.0
xmltodict==0.9.2
```

**Comment by spulec** [comment] 2015-10-14 19:14
Can you confirm you don't have any environment variables set related to AWS and don't have a [boto config file](http://boto.readthedocs.org/en/latest/boto_config_tut.html#details)?

I don't know why those would cause issues though, just trying to think of some possibilities.

**Comment by dmcclory** [comment] 2015-10-14 19:26
I do have a boto config file, it's very simple:

```
[s3]
calling_format = boto.s3.connection.OrdinaryCallingFormat
```
I use it as a workaround for this issue: https://github.com/boto/boto/issues/2836

**Comment by spulec** [comment] 2015-10-14 19:33
Ah, you will need to use `@mock_s3bucket_path` in place of `@mock_s3` for that to work. Sorry, the docs are pretty poor (non-existent) in regards to this.

**Comment by palewire** [comment] 2015-11-13 00:13
I am having this same problem. The root boto bug causing this is, I think, [here](https://github.com/boto/boto/issues/2836) and is one of the most annoying things in my life at the moment.

**Comment by spulec** [comment] 2015-11-14 17:54
@palewire does using `@mock_s3bucket_path` not work?

**Comment by danpoz** [comment] 2016-03-10 16:58
Same problem. Using mock_s3 and mock_s3bucket_path both fail.
Problem persists with and without setting the calling format as above.

If I remove the decorate and just use boto, it works fine.

pip freeze:
amqp==1.4.9
anyjson==0.3.3
boto==2.39.0
celery==3.1.19
chardet==2.0.1
cookies==2.2.1
cryptography==1.2.1
decorator==4.0.4
Django==1.8.7
django-appconf==0.4.1
django-celery==3.1.17
django-compressor==1.1.1
django-localflavor-us==1.1
django-transaction-hooks==0.2
django-waffle==0.8.1
enum34==1.1.2
factory-boy==2.4.1
future==0.15.2
futures==3.0.3
ipython==4.0.1
ipython-genutils==0.1.0
Jinja2==2.8
lxml==2.3.2
mock==1.0.1
moto==0.4.23
Pillow==3.0.0
pycrypto==2.6.1
pyOpenSSL==0.15.1
six==1.10.0

**Comment by spulec** [comment] 2016-05-02 02:07
Closing for now. Please reopen if still happening.

**Closed by spulec** 2016-05-02 02:07 UTC

**Comment by dekoza** [comment] 2018-03-08 10:33
@spulec can you please explain (or better add to docs) how to import and use `mock_s3bucket_path`?
