### ISSUE TITLE
Test session token used but not provided

### ISSUE THREAD

**Issue by cristina0botez** [spulec/moto#407] opened 2015-08-24 14:57 UTC
The `Key.generate_url` appends a session token to the URL even though one was not provided to the `S3Connection` constructor: `http://bucket-name.s3.amazonaws.com/location/file.txt?x-amz-security-token=test-session-token`.
I believe the problem occurs [here](https://github.com/spulec/moto/blob/72dbd349ac0e39d8cf642667a5f5002b8fd7af66/moto/core/responses.py#L261) - a flag should be provided to the `metadata_response` function to prevent adding this token if it is not required.

**Comment by spulec** [comment] 2015-08-30 23:15
I'm having some trouble reproducing. The following works for me

```python
import boto
from boto.s3.key import Key

from moto import mock_s3

@mock_s3
def test_generate_url():
    conn = boto.connect_s3()
    bucket = conn.create_bucket("foobar")

    key = Key(bucket)
    key.key = "the-key"
    key.set_contents_from_string("some stuff")
    assert "token" not in key.generate_url(expires_in=100)
```

Can you give some more details in what you are seeing?

**Comment by spulec** [comment] 2017-03-19 15:10
Going to close this out. Please reopen if it is still happening.

**Closed by spulec** 2017-03-19 15:10 UTC
