### ISSUE TITLE
With IAM mocks, get_user_policy returns a malformed policy document

### ISSUE THREAD

**Issue by dylanmccall** [spulec/moto#1650] opened 2018-05-24 20:54 UTC
I am using Moto's Python mocks to help write tests for an application that uses boto3's resource API to go through policy documents attached to users, buckets, and other things. I'm using moto==1.3.3 and boto3==1.7.21. However, it looks like user policies in particular are not behaving how I would expect. I'm including a script which reproduces the problem. It is possible to *put* a policy document for *iam_user_policy* using a json-formatted string, but when I attempt to retrieve that policy document, *iam_user_policy.policy_document* is a string (rather than a dict) that looks like this:

    {'policy_document': '{"Version": "2012-10-17", "Statement": [{"Resource": "*", "Action": "*", "Sid": "1", "Effect": "Allow"}]}', 'policy_name': 'test-user-1-policy-1', 'user_name': 'test-user-1'}

Looks like something should be returning just the "policy_document" field here, but instead it is returning the whole thing.

    #!/usr/bin/python3

    import json

    import boto3
    from moto import mock_iam

    with mock_iam():
        iam_service = boto3.resource('iam')

        user_policy = {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "1",
                    "Effect": "Allow",
                    "Action": "*",
                    "Resource": "*"
                }
            ]
        }

        iam_user = iam_service.create_user(UserName='test-user-1')
        iam_user_policy = iam_user.Policy(name='test-user-1-policy-1')
        iam_user_policy.put(PolicyDocument=json.dumps(user_policy))

        print(iam_user_policy.policy_document, "should equal", user_policy)

        response = iam_user.meta.client.get_user_policy(UserName='test-user-1', PolicyName='test-user-1-policy-1')
        print("This also happens with the resource API. Note the weird value for PolicyDocument:\n", response.get('PolicyDocument'))

One odd detail: normally iam_user_policy.policy_document is a dict, not a string, although this may be specific to the resource API. Perhaps it is appearing as a string because boto3 can't parse the response from Moto.

**Comment by spulec** [comment] 2018-05-31 03:59
I believe this is a dupe of https://github.com/spulec/moto/issues/1547#issuecomment-386799472

Feel free to reopen if I am wrong though.

**Closed by spulec** 2018-05-31 03:59 UTC

**Comment by dylanjsonar** [comment] 2018-05-31 22:53
Oops, I didn't find that one! Yep, this one's a dupe. Thank you :)
