### ISSUE TITLE
feature request: NotImplementedError: The get_query_results action has not been implemented

### ISSUE THREAD

**Issue by terence-cevo** [spulec/moto#5314] opened 2022-07-20 09:51 UTC
## Feature Request

Using moto to emulate Cloudwatch logs, and though `start_query` function is implemented the `get_query_results` function is not.

Need to read the result of the query started with the start_query command

## Expected Behaviour:

The `get_query_results` should return the result of the query  started using the `start_query` function.

## Actual Behaviour:
This is the trace of executing the `start_query` command followed by the `get_query_results` command.
```
self = <moto.logs.responses.LogsResponse object at 0x7f9a4d3af7d0>

    def call_action(self):
        headers = self.response_headers
    
        try:
            self._authenticate_and_authorize_normal_action()
        except HTTPException as http_error:
            response = http_error.description, dict(status=http_error.code)
            return self._send_response(headers, response)
    
        action = camelcase_to_underscores(self._get_action())
        method_names = method_names_from_class(self.__class__)
        if action in method_names:
            method = getattr(self, action)
            try:
                response = method()
            except HTTPException as http_error:
                response_headers = dict(http_error.get_headers() or [])
                response_headers["status"] = http_error.code
                response = http_error.description, response_headers
    
            if isinstance(response, str):
                return 200, headers, response
            else:
                return self._send_response(headers, response)
    
        if not action:
            return 404, headers, ""
    
        raise NotImplementedError(
>           "The {0} action has not been implemented".format(action)
        )
E       NotImplementedError: The get_query_results action has not been implemented
```

## Sample Code:

```
try:
        client = boto3.client("logs", "ap-southeast-2")
        response = client.start_query(
            logGroupName=os.environ['LOG_GROUP_NAME'],
            startTime=int(parser.parse(os.environ['START_DATE']).timestamp()),
            endTime=int(parser.parse(os.environ['END_DATE']).timestamp()),
            queryString="test"
        )
        query_id = response['queryId']
        events = client.get_query_results(queryId=query_id)
        print(events)
    except RuntimeError as e:
        print(e)

        raise e
```

**Comment by bblommers** [comment] 2022-07-26 01:17
Hi @terence-cevo, thanks for raising this! As far as I can tell, this is a duplicate of #5015, so I'll close this one. Please follow the other issues for updates around this.

**Closed by bblommers** 2022-07-26 01:17 UTC
