### ISSUE TITLE
Does moto handle *all* http connections?

### ISSUE THREAD

**Issue by nadersalehi** [spulec/moto#646] opened 2016-06-23 19:14 UTC
I am using moto to test an applications which in addition to AWS makes other HTTP calls.  When running the unit test, these HTTP calls fail due to connection error.  It seems to me that HTTPPretty is completely controlling all end points and not just the AWS ones.  Is it true and if so, how could I override it?

Thanks,
Nader

**Comment by bkersten** [comment] 2016-06-29 01:12
Hi Nader,

If you are seeing the error `httpretty.errors.UnmockedError: No mocking was registered, and real connections are not allowed (httpretty.allow_net_connect = False)`, then it is possible to allow unregistered endpoints to go through to the intended server by setting `allow_net_connect` to True.

```
import boto
from moto import mock_s3
import httpretty
import requests

mock = mock_s3()
mock.start()
httpretty.HTTPretty.allow_net_connect = True

conn = boto.connect_s3()
conn.create_bucket('mybucket')

requests.get('http://www.google.com')

mock.stop()
```

`allow_net_connect = True` looks to be the default so I'm not confident this is your problem

**Comment by spulec** [comment] 2016-07-10 01:18
HTTPPretty should only be overriding AWS endpoints, but it has been known to be a bit aggressive in the past. If you are having an issue, please reopen this issue with some test code.

This may also be a duplicate of https://github.com/spulec/moto/issues/303

**Closed by spulec** 2016-07-10 01:18 UTC
