### ISSUE TITLE
mock_sts throws ImportError: cannot import name 'sts_backend' from 'moto.sts' 

### ISSUE THREAD

**Issue by getglad** [spulec/moto#2935] opened 2020-04-29 17:12 UTC
I have been tracking https://github.com/spulec/moto/issues/2836 (relax version pins in setup.py for non-Py2 users, etc) and tested it against our code base. Many seem to be working but `mock_sts` is producing an `ImportError`.

At the bottom of this ticket, I have a sample test using `pytest` pulled from the `mock_sts` tests in `moto` that is producing the same error.  

I've reviewed a few dev releases and found the breaking build:

- works / passes with no errors:
   - 4/27 - pip install moto==1.3.15.dev758
- doesn't work / fails with an `ImportError` on `mock_sts`
   - 4/28 - pip install moto==1.3.15.dev765

Using `Python 3.7.3`

### Sample test sourced from https://github.com/spulec/moto/blob/master/tests/test_sts/test_sts.py#L56-L84
```
import pytest
import json
import boto3

from moto import mock_sts

ACCOUNT_ID = '123'

@mock_sts
def test_assume_role():
    client = boto3.client("sts", region_name="us-east-1")

    session_name = "session-name"
    policy = json.dumps(
        {
            "Statement": [
                {
                    "Sid": "Stmt13690092345534",
                    "Action": ["S3:ListBucket"],
                    "Effect": "Allow",
                    "Resource": ["arn:aws:s3:::foobar-tester"],
                }
            ]
        }
    )
    role_name = "test-role"
    s3_role = "arn:aws:iam::{account_id}:role/{role_name}".format(
        account_id=ACCOUNT_ID, role_name=role_name
    )
    assume_role_response = client.assume_role(
        RoleArn=s3_role,
        RoleSessionName=session_name,
        Policy=policy,
        DurationSeconds=900,
    )

    credentials = assume_role_response["Credentials"]
    assert credentials["SessionToken"] == 356
```

### Error when moto==1.3.15.dev765
 
```
================================================================ ERRORS ================================================================
___________________________________________________ ERROR collecting simple_test.py ____________________________________________________
ImportError while importing test module '<path_to>/simple_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
simple_test.py:11: in <module>
    @mock_sts
.venv/lib/python3.7/site-packages/moto/__init__.py:8: in f
    module = importlib.import_module(module_name, "moto")
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
.venv/lib/python3.7/site-packages/moto/sts/__init__.py:2: in <module>
    from .models import sts_backend
.venv/lib/python3.7/site-packages/moto/sts/models.py:5: in <module>
    from moto.core import BaseBackend, BaseModel
.venv/lib/python3.7/site-packages/moto/core/__init__.py:4: in <module>
    from .responses import ActionAuthenticatorMixin
.venv/lib/python3.7/site-packages/moto/core/responses.py:14: in <module>
    from moto.core.access_control import IAMRequest, S3IAMRequest
.venv/lib/python3.7/site-packages/moto/core/access_control.py:46: in <module>
    from moto.sts import sts_backend
E   ImportError: cannot import name 'sts_backend' from 'moto.sts' (<path_to>/.venv/lib/python3.7/site-packages/moto/sts/__init__.py)
=========================================================== warnings summary ===========================================================
.venv/lib/python3.7/site-packages/boto/plugin.py:40
  <path_to>/.venv/lib/python3.7/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================================================= short test summary info ========================================================
ERROR simple_test.py
```

**Comment by bblommers** [comment] 2020-05-01 05:59
This _might_ have been fixed by #2938 - will have a look later to confirm

**Comment by bblommers** [comment] 2020-05-01 13:02
Can't reproduce this anymore with 1.3.15.dev797, so will close this. 

Do let me know if I've missed anything

**Closed by bblommers** 2020-05-01 13:02 UTC
Labels: bug

**Comment by getglad** [comment] 2020-05-01 13:20
Agreed, `1.3.15.dev797` appears to clear our errors. Thanks!
