### ISSUE TITLE
Incorrect/incomplete EC2 DescribeVpcEndpointServicesResponse

### ISSUE THREAD

**Issue by kbalk** [spulec/moto#4233] opened 2021-08-27 20:50 UTC
Last year the code for `describe_vpc_endpoint_services` was committed, but the implementation markdown file wasn't updated to mark this API as implemented.  I assume that's because the code is incomplete?  I do know that the response for this API doesn't match what I'm seeing from AWS.

moto's response to this API:

```
<DescribeVpcEndpointServicesResponse xmlns="http://ec2.amazonaws.com/doc/2016-11-15/">
  <requestId>19a9ff46-7df6-49b8-9726-3df27527089d</requestId>
  <serviceNameSet/>
  <serviceDetailSet/>
</DescribeVpcEndpointServicesResponse>
```

AWS's response to this API:

```
<DescribeVpcEndpointServicesResponse xmlns="http://ec2.amazonaws.com/doc/2016-11-15/">
    <requestId>95501499-94d6-44fa-bf6c-cd556b0acd36</requestId>
    <serviceDetailSet>
        <item>
            <acceptanceRequired>false</acceptanceRequired>
            <availabilityZoneSet>
                <item>us-east-1a</item>
                <item>us-east-1b</item>
                <item>us-east-1c</item>
                <item>us-east-1d</item>
                <item>us-east-1e</item>
                <item>us-east-1f</item>
            </availabilityZoneSet>
            <baseEndpointDnsNameSet>
                <item>config.us-east-1.vpce.amazonaws.com</item>
            </baseEndpointDnsNameSet>
            <managesVpcEndpoints>false</managesVpcEndpoints>
            <owner>amazon</owner>
            <privateDnsName>config.us-east-1.amazonaws.com</privateDnsName>
            <privateDnsNameVerificationState>verified</privateDnsNameVerificationState>
            <privateDnsNameSet>
                <item>
                    <privateDnsName>config.us-east-1.amazonaws.com</privateDnsName>
                </item>
            </privateDnsNameSet>
            <serviceId>vpce-svc-xxxxxxxxxxxx</serviceId>
            <serviceName>com.amazonaws.us-east-1.config</serviceName>
            <serviceType>
                <item>
                    <serviceType>Interface</serviceType>
                </item>
            </serviceType>
            <tagSet/>
            <vpcEndpointPolicySupported>true</vpcEndpointPolicySupported>
        </item>
    </serviceDetailSet>
    <serviceNameSet>
        <item>com.amazonaws.us-east-1.config</item>
    </serviceNameSet>
</DescribeVpcEndpointServicesResponse>
```

**Comment by kbalk** [comment] 2021-08-29 02:54
I made an attempt to debug this problem, but it would take me a while to understand the interplay of the various route, subnet and VPC objects.  Perhaps when someone is working in this area they could take a look at it.

I do have a test case which I've attached as a zipped tar file at the end of this comment.  There's a `README.txt` in the tar file with some info about how to run the test case (basically a Terraform file).  

I did notice a few things:

- `self.vpc_end_points` is empty, which is why the template isn't being populated.  
- There are some VPC fields which moto doesn't have (privateDnsName, privateDnsVerification, tagSet), but would probably be ok omitting from the template, although the service ID might be useful if moto had it.
- moto is working with `module.vpc.aws_subnet.private`, but aws is working with `module.vps.aws_route_table`.  I don't know why they're looking at different modules.  Maybe this is why VPC endpoints aren't being created?  

Note: the tar file also includes both the aws and moto Terraform logs under the `logs` directory.
[describe_vpc_endpoint_service.tar.gz](https://github.com/spulec/moto/files/7071819/describe_vpc_endpoint_service.tar.gz)

**Comment by bblommers** [comment] 2021-08-31 14:55
Hey @kbalk!

> the implementation markdown file wasn't updated to mark this API as implemented. I assume that's because the code is incomplete?

The markdown file is updated automatically using a script - as long as the method-name in EC2Backend corresponds with the feature-name, it is marked as implemented.
The EC2 backend uses a different name though, `get_vpc_endpoint_services`, so that's why the script doesn't know it is implemented.

With respect to the difference between Moto and AWS:
From what I can see, AWS has default endpoint services that are always returned. Moto only returns custom endpoint services, that have been created manually using `create_vpc_endpoint()`.
So the solution might be as simple as hardcoding a bunch of default services, and returning those alongside any user-created ones.

**Comment by kbalk** [comment] 2021-08-31 16:18
> So the solution might be as simple as hardcoding a bunch of default services, and returning those alongside any user-created one

Beyond hardcoding the default services, those default services would then need to be run through `get_vpc_endpoint_services` as well, wouldn't they?

**Comment by bblommers** [comment] 2021-08-31 16:23
What do you mean by 'run through'?
I meant that `get_vpc_endpoint_services ` would return the default services (appropriately filtered ofcourse).

**Comment by kbalk** [comment] 2021-09-16 16:30
`create_vpc_endpoint_service_configuration` isn't implemented, which would provide the info for `describe_vpc_endpoint_services`.

**Comment by kbalk** [comment] 2021-09-17 01:13
@bblommers I think I understand this API now: each AWS service has a private DNS name created for it along with an assigned serviceId and serviceName, and a serviceType of "Interface".  Some services also have a serviceType of "Gateway" and some have more than one baseEndpointDnsName.  I can use the output of the `describe_vpc_endpoint_services` API called from AWS as a guideline.

The problem is collecting all the info in one place and only for the services loaded (although I wasn't sure on that last point).  I was thinking I could do the following, but please let me know if you have a better idea:

- `class BaseBackend`: define a new method `default_vpc_endpoint_services()` that when invoked would return ServiceDetails (the baseEndpointDnsNames, privateDnsNames, serviceId, serviceName, serviceType, etc).  This info wouldn't change.
- `class MotoAPIBackend`:  define a new method `all_default_vpc_endpoint_services()` that when invoked would call the `default_vpc_endpoint_service()` method for all the loaded backends.
- `class VPCBackend` has the newly renamed `describe_vpc_endpoint_services` method that could invoke `moto_api_backend.all_default_vpc_endpoint_services()` to retrieve the list of ServiceDetails and use that info for the API's response.  The downside of this would be re-generating the list of ServiceDetails every time the API was issued.

Alternatively, the list of ServiceDetails could be created once all the backends were loaded.  Does this sound ok?

**Comment by kbalk** [comment] 2021-09-17 21:43
I did an initial comparison of the service names from the AWS response to `describe_vpc_endpoint_services()` to the directories names found in `moto/moto`.  I'm not sure I mapped the services names to the directories correctly, whether I missed some mappings or whether all mappings are applicable.  I'll update this list to include which have an interface and gateway.

Note: the AWS service names are preceded by 'com.amazonaws.<region>.'

Moto directories      | Possibly equivalent AWS service names
--------------------- | -----------------------------------------
acm | acm-pca
apigateway |
applicationautoscaling | application-autoscaling
athena | athena
autoscaling | autoscaling, autoscaling-plans
awslambda | lambda
batch |
cloudformation | cloudformation
cloudwatch |
codecommit | codecommit
codepipeline | codepipeline
cognitoidentity |
cognitoidp |
config | config
datapipeline |
datasync | datasync
dms | dms
dynamodb | dynamodb
dynamodb2 |
dynamodbstreams |
ec2 | ec2
ec2instanceconnect |
ecr | ecr.api, ecr.dkr
ecs | ecs, ecs-agent, ecs-telemetry
efs |
eks |
elasticbeanstalk | elasticbeanstalk, elasticbeanstalk-health
elastictranscoder |
elb | elastic-inference.runtime, elasticbeanstalk-health, elasticfilesystem, slasticfilesystem-fips, elasticloadbalanceing, elasticmapreduce
elbv2 |
emr | emr-containers
events | events
firehose | kinesis-firehose
forecast |
glacier |
glue | glue
iam |
instance_metadata |
iot | iot.data, iotsitewise.api, iotsitewise.data, iowireless.api
iotdata |
kinesis | kinesis-streams
kinesisvideo |
kinesisvideoarchivedmedia |
kms | kms
logs | logs
managedblockchain |
mediaconnect |
medialive |
mediapackage |
mediastore |
mediastoredata |
opsworks |
organizations |
polly |
ram |
rds | rds, rds-data
rds2 |
redshift | redshift, redshift-data, redshift-fips
resourcegroups |
resourcegroupstaggingapi |
route53 |
s3 | s3
s3bucket_path |
sagemaker | sagemaker.api, sagemaker.featurestore-tuntime, sagemaker-runtime, sagemaker.runtime-fips (also services aws.sagemaker.region.notebook, aws.sagemaker.region.studio)
secretsmanager | sms, sms-fips
ses |
sns | sns
sqs | sqs
ssm | ssm, ssmmessages
stepfunctions |
sts | sts
support |
swf |
transcribe | transcribe, transcribestreaming
wafv2 |
xray | xray

**Comment by bblommers** [comment] 2021-09-17 23:09
Thanks for the investigation @kbalk. That sounds like a good approach overall. Two minor points:

> class MotoAPIBackend: define a new method all_default_vpc_endpoint_services() that when invoked would call the default_vpc_endpoint_service() method for all the loaded backends.
>

The MotoAPI should really be reserved for operations that are specific to Moto, independent of AWS. So the method is a good idea, but this may be better placed somewhere else - maybe just part of `VPCBackend`?
Alternatively just a separate service/utility class, to ensure that this logic is independent (and independently testable) from other EC2 logic.

> Alternatively, the list of ServiceDetails could be created once all the backends were loaded. Does this sound ok?
> 

Generating this list once could lead to a bug where people use context managers:
```
@mock_sts
@mock_ec2
def test():
    describe_vpc_endpoint_services()  # Generates the list with EC2 and STS
    with mock_transcribe():
        # do other things
        describe_vpc_endpoint_services()  # Generates the list with EC2 and STS - but this should now also include Transcribe
```
Granted, it's a edge use case - but it would lead to unexpected behaviour, which is never good. I don't imagine generating the list would take that long anyway, so let's just regenerate every time. We can revisit that assumptions if it turns out to be too optimistic.

**Comment by kbalk** [comment] 2021-09-22 00:42
#4322

**Closed** 2021-09-24 16:02 UTC
Labels: enhancement
