### ISSUE TITLE
Slow S3 key creation boto3

### ISSUE THREAD

**Issue by ptimsonbbc** [spulec/moto#610] opened 2016-05-08 23:15 UTC
It seems to take around 5000ms to put a new key of 8MiB string in an S3 bucket. Where as writing the string to disk takes ~30ms. Is there something I am doing wrong? Can I speed this up?
```
import os
import time
import boto3
from moto import mock_s3

FILE_SIZE = 8 * 1024 * 1024

# Setup Mock S3 in context
mock = mock_s3()
mock.start()

# Create Connection & Bucket
BUCKET = 's3mock'
s3 = boto3.resource('s3')
s3.create_bucket(Bucket=BUCKET)

# Generate String
rand_string = os.urandom(FILE_SIZE)

# Write to disk
start = time.time()
with open('rand.txt', 'a') as the_file:
    the_file.write(rand_string)
print("Duration: {0}".format(time.time() - start))

# Create S3 Key
start = time.time()
s3.Object(BUCKET, '1').put(Body=rand_string)
print("Duration: {0}".format(time.time() - start))
mock.stop()
```

Thanks in advance! 

**Update:**
I tried the same test with S3 Ninja and it took ~150ms

**Comment by ptimsonbbc** [comment] 2016-05-11 21:18
After diging a little futher, I believe this may be due to the server not being to able large payloads.

**Comment by ptimsonbbc** [comment] 2016-05-12 09:34
I can confirm that using the external server moto_server s3 - speeds things up significaly. It can now create the key in 90ms. Confirming the problem lies around the HTTPretty / starting the mocking with mock.start

```
import os
import time

import botocore.endpoint
def _get_proxies(self, url):
    return {'http': 'http://127.0.0.1:5000/', 'https': 'https://127.0.0.1:5000/'}
botocore.endpoint.EndpointCreator._get_proxies = _get_proxies
import boto3

FILE_SIZE = 8 * 1024 * 1024

# Create Connection & Bucket
BUCKET = 's3mock'
s3 = boto3.resource('s3', endpoint_url='http://127.0.0.1:5000')
s3.create_bucket(Bucket=BUCKET)

# Generate String
rand_string = os.urandom(FILE_SIZE)

# Create S3 Key ~90ms
start = time.time()
key = s3.Object(BUCKET, '1')
key.put(Body=rand_string)

print("Duration: {0}".format(time.time() - start))
```

**Comment by ptimsonbbc** [comment] 2016-05-12 09:59
Testing HTTPretty lib directly seems to perform fine

```
import os

import requests
import httpretty
import time

os.environ['no_proxy'] = 'test.local'

FILE_SIZE = 8 * 1024 * 1024
rand_string = os.urandom(FILE_SIZE)

httpretty.enable()
httpretty.register_uri(httpretty.PUT, "http://test.local",
                       body=rand_string)

start = time.time()
response = requests.put('http://test.local')
print("Duration: {0}".format(time.time() - start))

httpretty.disable()
httpretty.reset() 
```

**Comment by spulec** [comment] 2016-06-18 23:43
Sounds like the issue is at https://github.com/gabrielfalcao/HTTPretty/issues/296

I'm going to close this, but let me know if you disagree

**Closed by spulec** 2016-06-18 23:43 UTC

**Comment by ptimsonbbc** [comment] 2016-06-20 08:39
Hey @spulec the problem is with HTTPretty so yeah posted it over there. It's a while since I looked at this stuff now but hopefully they can fix it!
