### ISSUE TITLE
credentials mocking

### ISSUE THREAD

**Issue by sean-abbott** [spulec/moto#889] opened 2017-04-03 22:51 UTC
This is either a question or a request. 

I've been unable to find any references to credentials profiles in the code, so I'm guessing these aren't implemented yet.  

I'm using different profiles for different groups, and I need to make my s3 connection using profile (i.e., `aws_session = boto3.Session(profile_name=profile_name)`

moto does not appear to mock the profile name; it must exist in the developers `~/.aws/credentials` (or config).

Any chance this can be implemented and that other folks need it?

**Comment by spulec** [comment] 2017-04-13 01:13
When you say `moto does not appear to mock the profile name`, what are you seeing to indicate that? Are you making some IAM calls? For the most part, Moto ignores all of the credentials as of now.

If you could add some code, that might help me understand the use case.

**Comment by sean-abbott** [comment] 2017-04-13 14:41
I've since forgotten the specifics, but I think it comes down to calling boto3.Session with a profile or attempting to use it caused it to look for (and not find) the `~/.aws/credentials|config` file. 

I fixed by manually mocking the call expanduser call. 

If I am doing this poorly, please do let me know (especially if you can suggest a fix!) I'm not great at testing.

https://github.com/sean-abbott/terraform.py/blob/master/tests/remote/test_s3.py

**Comment by spulec** [comment] 2017-04-14 01:24
Hmmmm. What happens if you don't mock the credentials?

**Comment by sean-abbott** [comment] 2017-04-14 13:50
botocore.exceptions.ProfileNotFound: The config profile (testawsprofile) could not be found

call is in test_get_remote_state, calling ati.remote.s3_remote_state.get_remote_state (line 69)

s3_remote_state.py:36:  `aws_session = boto3.Session(profile_name=profile_name`

This happens if I comment line 60 in tests/remote/test_s3.py (which is where I patch expanduser)

**Comment by JackDanger** [comment] 2017-04-27 03:03
@sean-abbott Apologies, I tried to find where you were mocking the credentials but I'm not sure I found the right place. Is it this?: https://github.com/sean-abbott/terraform.py/commit/d2ed646648d0b884da972ee612822a4fb0c590db

**Comment by JackDanger** [comment] 2017-07-17 22:38
@sean-abbott I'm going to close this for now but please reopen when you get the chance.

**Closed by JackDanger** 2017-07-17 22:38 UTC

**Comment by dan-coates** [comment] 2018-10-30 21:05
I think I've come across this same issue and have a relatively easy way to reproduce it. Essentially, if the AWS_PROFILE environment variable is set but the profile isn't found in ~/.aws/config, it raises an exception on import:

```
________________________________________ ERROR collecting tests/test_create_cluster.py _________________________________________
tests/test_create_cluster.py:2: in <module>
    from moto import mock_s3
venv/lib/python3.6/site-packages/moto/__init__.py:9: in <module>
    from .apigateway import mock_apigateway, mock_apigateway_deprecated  # flake8: noqa
venv/lib/python3.6/site-packages/moto/apigateway/__init__.py:2: in <module>
    from .models import apigateway_backends
venv/lib/python3.6/site-packages/moto/apigateway/models.py:648: in <module>
    for region_name in Session().get_available_regions('apigateway'):
venv/lib/python3.6/site-packages/boto3/session.py:80: in __init__
    self._setup_loader()
venv/lib/python3.6/site-packages/boto3/session.py:120: in _setup_loader
    self._loader = self._session.get_component('data_loader')
venv/lib/python3.6/site-packages/botocore/session.py:729: in get_component
    return self._components.get_component(name)
venv/lib/python3.6/site-packages/botocore/session.py:946: in get_component
    self._components[name] = factory()
venv/lib/python3.6/site-packages/botocore/session.py:186: in <lambda>
    lambda:  create_loader(self.get_config_variable('data_path')))
venv/lib/python3.6/site-packages/botocore/session.py:281: in get_config_variable
    elif self._found_in_config_file(methods, var_config):
venv/lib/python3.6/site-packages/botocore/session.py:308: in _found_in_config_file
    return var_config[0] in self.get_scoped_config()
venv/lib/python3.6/site-packages/botocore/session.py:385: in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
E   botocore.exceptions.ProfileNotFound: The config profile (~~~my-aws-profile-name~~~) could not be found
```

If I `unset AWS_PROFILE`, it's totally fine with there being no ~/.aws/config at all. Since it's fine if config doesn't exist, it makes me think that it should tolerate a specific profile not being there.

**Comment by drorata** [comment] 2018-11-07 08:03
I suspect I'm witnessing a related, but different, issue. When I run the tests locally everything is fine (and I have the AWS credentials in `~/.aws`). Once I try to run the tests within a docker container (which doesn't contain the credentials) I get the following error:

```
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

This is thrown right after appearances of:

```python
s3_conn = boto3.client('s3', 'us-west-2')
s3_conn.create_bucket(Bucket='test-bucket')
```

If, when I start the container, I mount my credentials the tests all pass.
