### ISSUE TITLE
Is there a way to use an cloudformation template to mock all supported objects?

### ISSUE THREAD

**Issue by gcavalcante8808** [spulec/moto#1950] opened 2018-11-15 15:42 UTC
Hi Folks,

I'd like to use an cloudformation.yaml or json file to mock all supported resources. Is there any way to do it currently?

I just read the https://github.com/spulec/moto/issues/406 issue, but I cant create all resources using a cf stack, It just returns a mocked json with stack info (as expected).

Thanks in Advance.

**Comment by kgutwin** [comment] 2018-11-16 20:04
I don't think there's something already built into moto, but I have had luck reading in the CFN file with a YAML parser and feeding the contents of the resource Properties block directly as `**kwargs` to the appropriate `client.create_whatever()` method. Specifically, for me this works with DynamoDB tables; I haven't tried anything else.

```python
from moto import mock_dynamodb2
import boto3
import yaml

template = yaml.load(open('mytemplate.yaml'))

tabledef = template['Resources']['MyTable']['Properties']
with mock_dynamodb2():
    dynamo = boto3.client('dynamodb')
    dynamo.create_table(**tabledef)
```

There are two caveats that I discovered when parsing CloudFormation. First, CloudFormation's custom YAML tags (like `!Ref`) can mess up a stock YAML parser. To work around that, I added these class definitions before calling `yaml.load`... there is some metaclass magic that causes them to automatically register with the YAML parser.

```python
class ScalarObject(yaml.YAMLObject):
    def __init__(self, val):
        self.val = val
        
    @classmethod
    def from_yaml(cls, loader, node):
        return cls(node.value)

class Ref(ScalarObject):
    yaml_tag = '!Ref'

class Sub(ScalarObject):
    yaml_tag = '!Sub'

class GetAtt(ScalarObject):
    yaml_tag = '!GetAtt'
```

This doesn't actually interpret the tags, though, so that's the second caveat -- if you use these types of references, you will probably need to manually plug in values after you've loaded the raw template. For example, in my template, the DynamoDB table names are generated with a `!Ref` function, so I just do a quick substitution of `TableName` with an appropriate value before the call to `create_table()`.

Hope this helps, YMMV.

**Comment by gcavalcante8808** [comment] 2018-11-16 20:12
After looking at the tests, I just understand that it mocks every supported statement, but you need to mock the needed resources as well, Eg.
```

import os
import boto3
import pytest

import app


from moto import mock_s3, mock_elbv2, mock_ec2, mock_cloudformation


# Mock Everything!
mock_cloudformation().start()
mock_elbv2().start()

@pytest.fixture
def client():
    client = app.ELBRouteUpdater(source_rule_type=app.ListenerType.FORWARD,
                                 source_path='/manut',
                                 target_rule_type=app.ListenerType.REDIRECT,
                                 target_path='status.mercos.com'
    )
    return client


class TestELBRouterUpdater:
    @mock_cloudformation
    @mock_elbv2
    @pytest.fixture
    def infra(self, client):
        cf = boto3.client('cloudformation', 
                                region_name=client.s3_region,
                                aws_access_key_id=client.s3_access_key,
                                aws_secret_access_key=client.s3_secret_key
        )

        with open ('elb.yaml', 'rb') as cfile:
            template = cfile.read().decode()

        cf.create_stack(StackName='mock',TemplateBody=template)

        elb = boto3.client('elbv2', 
                            region_name=client.s3_region,
                            aws_access_key_id=client.s3_access_key,
                            aws_secret_access_key=client.s3_secret_key
        )

        self.elb = elb
        return cf

    def test_get_listener(self, infra, client):
        raise NotImplementedError
```

With this, the elbv2 object is returned with the information place in the elb.yml cf file. 

Maybe some examples would be nice to intervene in the learning curve...

I'm willing to PR a doc with something about it if the team thinks the same.

**Comment by spulec** [comment] 2018-12-29 01:45
A PR to the docs would be great!

**Comment by spulec** [comment] 2020-02-19 03:26
I think this is a duplicate of https://github.com/spulec/moto/issues/2076, but feel free to reopen if I am reading it wrong.

**Closed by spulec** 2020-02-19 03:26 UTC
