### ISSUE TITLE
Test suite created real stuff

### ISSUE THREAD

**Issue by jeffcasavant** [spulec/moto#1877] opened 2018-10-16 17:04 UTC
I have been having encapsulation issues with Moto on Python 3.7.0.  When I run the test suite with `make test` and the AWS environment variables set (`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`), I ended up with ~18 ELBs created on my account (though it could have been more, we hit our limit).~ quite a few things created on my account:

* ELBs
* DynamoDB tables
* ECR repos
* Subnets, vpcs, etc.
* CloudFormation
* SES
* SQS
* SNS

This is with Python 3.7.0 in a virtualenv.

```
pip install -r requirements-dev.txt
```

The following packages were installed:

```
asn1crypto==0.24.0
atomicwrites==1.2.1
attrs==18.2.0
aws-xray-sdk==0.95
backports.ssl-match-hostname==3.5.0.1
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.6.0
boto==2.49.0
boto3==1.9.24
botocore==1.12.24
certifi==2018.10.15
cffi==1.11.5
chardet==3.0.4
click==6.7
configparser==3.5.0
cookies==2.2.1
coverage==4.5.1
cryptography==2.3.1
docker==3.5.0
docker-pycreds==0.3.0
docutils==0.14
ecdsa==0.13
enum34==1.1.6
flake8==3.5.0
Flask==1.0.2
freezegun==0.3.11
funcsigs==1.0.2
future==0.16.0
futures==3.2.0
idna==2.7
inflection==0.3.1
ipaddress==1.0.22
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
jsondiff==1.1.1
jsonpickle==1.0
lxml==4.2.3
MarkupSafe==1.0
mccabe==0.6.1
mock==2.0.0
more-itertools==4.3.0
-e git+https://github.com/spulec/moto.git@2bb3d07e113931df96b98f16be6e4336863509f4#egg=moto
nose==1.3.7
pathlib2==2.3.2
pbr==4.3.0
pluggy==0.8.0
prompt-toolkit==1.0.14
py==1.7.0
pyaml==17.12.1
pycodestyle==2.3.1
pycparser==2.19
pycryptodome==3.6.6
pyflakes==1.6.0
pytest==3.8.2
python-dateutil==2.7.3
python-jose==2.0.2
pytz==2018.5
PyYAML==3.13
requests==2.19.1
responses==0.9.0
s3transfer==0.1.13
scandir==1.9.0
six==1.11.0
sure==1.4.11
urllib3==1.23
wcwidth==0.1.7
websocket-client==0.53.0
Werkzeug==0.14.1
wrapt==1.10.11
xmltodict==0.11.0
```

I ran (because I knew it would take a while and I wanted a log of failed tests):

```
make test 2>&1 | tee ~/moto-test-log
```

I've attached the log.
[moto-test-log.txt](https://github.com/spulec/moto/files/2484225/moto-test-log.txt)

**Comment by spulec** [comment] 2018-10-17 03:35
Sorry about that. I believe this is a duplicate of https://github.com/spulec/moto/issues/1793. We are still working on a long-term fix. The short-term fix is to downgrade boto3 versions.

**Closed** 2018-10-18 03:51 UTC
