### ISSUE TITLE
DynamoDB: ProjectionExpression not working on get_item()

### ISSUE THREAD

**Issue by janluak** [spulec/moto#4370] opened 2021-10-05 08:00 UTC
On the mock of the dynamo_db resource the query function is handling the ProjectionExpression correctly.
Yet, the get_item function is returning an empty response (only Metadata) instead of the item limited to specified attributes.

moto: v2.2.6
boto3: v1.17.79

```
import boto3

dynamo_db_resource = boto3.resource("dynamodb")
table = dynamo_db_resource.Table("TableName")

# empty response
table.get_item(Key={"pk": pk}, ProjectionExpression="expected_attribute_name")

# working response
table.query(IndexName="index_name", KeyConditionExpression={"index_pk": "index_pk_value"}, ProjectionExpression="expected_attribute_name")

```

**Comment by k0mmsussert0d** [comment] 2021-10-13 12:55
Hi @janluak 
I wanted to take care of this issue, but I'm unable both to understand the problem and reproduce it. As far as I can tell, projection expressions work fine with `get_item` and there are multiple unit tests confirming it. It would be very helpful if you could provide the full code to reproduce the issue, including table creation, inserting items etc..

The call you marked as "working" has no chance to work, because `KeyConditionExpression` excepts `str` instead of `dict` so `ParamValidationError` is thrown. Did you mean to use legacy `KeyConditions`?

**Comment by bblommers** [comment] 2021-11-11 11:08
I'll close this - thanks for the investigation @k0mmsussert0d.
Do let us know if you're still having issues though @janluak

**Closed by bblommers** 2021-11-11 11:08 UTC
Labels: bug
