### ISSUE TITLE
Moto running into thread-safety issues

### ISSUE THREAD

**Issue by jpalawaga** [spulec/moto#372] opened 2015-07-07 21:17 UTC
Having some issues with moto returning exceptions when it's being called with threaded code.

Here is some of the moto log leading up to the key error:
```
127.0.0.1 - - [07/Jul/2015 20:44:48] "PUT /local-output/bac17946-1b52-4676-bdbc-5dc56cccc8a0/e48207bd-48b1-4b17-90b1-d8164ebac2bc/1_0_1.json HTTP/1.1" 200 -
127.0.0.1 - - [07/Jul/2015 20:44:48] "HEAD /local-output/ HTTP/1.1" 200 -
127.0.0.1 - - [07/Jul/2015 20:44:48] "GET /local-output/?prefix=5ab1ce7d-e8e7-45b2-8673-313d757a38f5/44fb25dc-38e6-4e8c-ae55-1f9fe3c90cfb HTTP/1.1" 500 -
127.0.0.1 - - [07/Jul/2015 20:44:48] "PUT /local-output/bac17946-1b52-4676-bdbc-5dc56cccc8a0/df2d0ae3-4047-4a46-b53b-a6d68da68a63/2_2_2.json HTTP/1.1" 200 -
127.0.0.1 - - [07/Jul/2015 20:44:48] "HEAD /local-output/ HTTP/1.1" 200 -
127.0.0.1 - - [07/Jul/2015 20:44:48] "PUT /local-output/bac17946-1b52-4676-bdbc-5dc56cccc8a0/75c7c110-fdbb-4b93-82c8-17669454cd4c/1_0_1.json HTTP/1.1" 200 -
127.0.0.1 - - [07/Jul/2015 20:44:48] "PUT /local-output/bac17946-1b52-4676-bdbc-5dc56cccc8a0/59ccf22d-2dbc-4d0e-9ce6-589b302cd0d6/3_2_2.json HTTP/1.1" 200 -
127.0.0.1 - - [07/Jul/2015 20:44:48] "PUT /local-output/bac17946-1b52-4676-bdbc-5dc56cccc8a0/e0b2fb8f-68b1-49e1-82c6-ac6f643d8276/3_1_1.json HTTP/1.1" 200 -
127.0.0.1 - - [07/Jul/2015 20:44:48] "PUT /local-output/bac17946-1b52-4676-bdbc-5dc56cccc8a0/e63daa84-c948-4a7c-b44a-dc9ed7028aca/3_6_2.json HTTP/1.1" 200 -
127.0.0.1 - - [07/Jul/2015 20:44:48] "GET /local-output/?prefix=5ab1ce7d-e8e7-45b2-8673-313d757a38f5/4fa9e78c-e5c7-4fde-9648-efca0a7d2221 HTTP/1.1" 200 -
127.0.0.1 - - [07/Jul/2015 20:44:48] "PUT /local-output/bac17946-1b52-4676-bdbc-5dc56cccc8a0/498ab0b9-bf7f-404d-b7db-a080308044a0/2_2_1.json HTTP/1.1" 200 -
127.0.0.1 - - [07/Jul/2015 20:44:48] "PUT /local-output/bac17946-1b52-4676-bdbc-5dc56cccc8a0/b506ece9-b65c-4eab-96ea-79dff2cbde8e/2_3_3.json HTTP/1.1" 200 -
```

```
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/moto/server.py", line 53, in __call__
    return backend_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/moto/core/utils.py", line 77, in __call__
    result = self.callback(request, request.url, {})
  File "/usr/local/lib/python2.7/dist-packages/moto/s3bucket_path/urls.py", line 10, in bucket_response2
    return ro.bucket_response(*args)
  File "/usr/local/lib/python2.7/dist-packages/moto/s3/responses.py", line 32, in bucket_response
    response = self._bucket_response(request, full_url, headers)
  File "/usr/local/lib/python2.7/dist-packages/moto/s3/responses.py", line 55, in _bucket_response
    return self._bucket_response_get(bucket_name, querystring, headers)
  File "/usr/local/lib/python2.7/dist-packages/moto/s3/responses.py", line 121, in _bucket_response_get
    result_keys, result_folders = self.backend.prefix_query(bucket, prefix, delimiter)
  File "/usr/local/lib/python2.7/dist-packages/moto/s3/models.py", line 308, in prefix_query
    for key_name, key in bucket.keys.items():
  File "/usr/local/lib/python2.7/dist-packages/moto/s3/utils.py", line 92, in items
    return list(self.iteritems())
  File "/usr/local/lib/python2.7/dist-packages/moto/s3/utils.py", line 75, in _iteritems
    for key in self:
RuntimeError: dictionary changed size during iteration
```

**Comment by spulec** [comment] 2015-07-15 01:35
Thanks for opening.

Moto isn't really setup to be used in a multi-threaded situation right now. I'm not sure exactly what changes would need to be made, but it seems non-trivial. I'm not going to have any time soon to take a look, but would be happy to accept a pull request if someone else gets some time.

**Comment by spulec** [comment] 2015-08-08 13:41
Going to close this as a dupe of #313

**Closed by spulec** 2015-08-08 13:41 UTC
