### ISSUE TITLE
Incompatible botocore version

### ISSUE THREAD

**Issue by ghandic** [spulec/moto#5598] opened 2022-10-25 03:09 UTC
Recently we had unexplainable pipeline failures with our testing, found out this was because botocore was recently released with a breaking change. We have moto pinned in our requirements.txt tests but it requires `botocore>=1.12.201` (see below link).  So 3/4 hours before our pipeline failed there was a release to botocore for 1.28.0. Ideally this could be more explicit on the dependencies. For now we have pinned botocore for our testing requirements.

https://github.com/spulec/moto/blob/c0b581aa08b234ed036c43901cee84cc9e955fa4/setup.py#L31

**Comment by bblommers** [comment] 2022-10-25 21:12
Hi @ghandic, do you have a reproducible test case for this? Our own internal tests still work fine with `botocore==1.28.0` and `boto3==1.25.0`

**Comment by ghandic** [comment] 2022-10-25 21:51
I'll try to get one up, we're using pynamodb which relies on some of the Botocore functionality

**Comment by bblommers** [comment] 2022-11-26 11:07
Looks like this was a [PynamoDB](https://github.com/pynamodb/PynamoDB/issues/1081) issue, so I'll close this.

**Closed by bblommers** 2022-11-26 11:07 UTC
Labels: debugging
