### ISSUE TITLE
S3 key with slash

### ISSUE THREAD

**Issue by rampage644** [spulec/moto#630] opened 2016-06-07 14:07 UTC
I've found that using key with slash(`/`) in it doesn't work for Object operations.

``` python
import boto3
import moto
import pytest


@pytest.mark.parametrize('key', ['key.txt', '/key.txt'])
def test_foo(key):
    with moto.mock_s3():
        conn = boto3.resource('s3')
        bucket = conn.Bucket('mybucket')
        bucket.create()
        obj = bucket.Object(key)
        # put()
        obj.put('ABC')
```

Second case fails with 
`ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://mybucket.s3.amazonaws.com//key.txt".`

Can you check if it's bug or not?

**Comment by spulec** [comment] 2016-06-19 00:33
It is definitely a bug, but I'm having trouble getting to the bottom of it

**Comment by snordhausen** [comment] 2017-01-25 17:42
It seems this is an issue with httpretty. To create the key, boto3 sends a "PUT //key.txt HTTP/1.1" command to Amazon. However, httpretty has problems with the double slash:
```
import requests
import httpretty
httpretty.enable()
print requests.get('http://github.com//spulec').content
```
This code raises an exception. When httpretty is not enabled, the code works. Note the double slash in **github.com//spulec**.

**Comment by spulec** [comment] 2017-02-09 02:45
Thanks for the work. Seems like we will need to wait on that.

**Comment by RDProjekt** [comment] 2019-08-14 13:00
This still does not work, and HTTPretty has not been fixed, but the bug in HTTPretty is not the cause. See #1637 for the details, it's related to `url_paths` in `s3/urls.py` and a bug in Werkzueg in server mode.

**Comment by spulec** [comment] 2020-02-19 04:13
I think this is fixed with https://github.com/spulec/moto/pull/2398/files, but feel free to reopen if it still doesn't work.

**Closed by spulec** 2020-02-19 04:13 UTC
