### ISSUE TITLE
Feature request: API Gateway: update_rest_api()

### ISSUE THREAD

**Issue by benkeil** [spulec/moto#3061] opened 2020-06-10 12:49 UTC
I use the latest motoserver/moto docker image.

I try to run terraform against the moto server. During refreshing the state I got the following error.

terraform output

```
module.base.aws_api_gateway_rest_api.widgets: Refreshing state... [id=i0lmkj9fi9]
```

moto server output

```
172.17.0.1 - - [10/Jun/2020 12:45:41] "GET /restapis/i0lmkj9fi9 HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3.6/site-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/moto/server.py", line 135, in __call__
    return backend_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/moto/core/utils.py", line 146, in __call__
    result = self.callback(request, request.url, {})
  File "/usr/lib/python3.6/site-packages/moto/apigateway/responses.py", line 56, in restapis_individual
    rest_api = self.backend.get_rest_api(function_id)
  File "/usr/lib/python3.6/site-packages/moto/apigateway/models.py", line 539, in get_rest_api
    rest_api = self.apis[function_id]
KeyError: 'i0lmkj9fi9'
```

**Comment by benkeil** [comment] 2020-06-12 09:42
```terraform
resource "aws_api_gateway_rest_api" "widgets" {
  name        = "widgets"
  description = "Provide endpoints for the widgets API"
}
```

It's nothing special. The problem occurs only when you already have a terraform state (in my case a local state) and terraform try to sync the resources at the beginning. When I delete the file before apply its works.

**Comment by bblommers** [comment] 2020-06-14 08:47
Yup, I can reproduce that. 
Looks like we don't support updates for REST API's at all: https://github.com/spulec/moto/blob/master/moto/apigateway/responses.py#L107

Marking this as an enhancement - I'll also update the title to reflect this

**Comment by rajendersaini** [comment] 2021-09-17 03:51
@bblommers - what is left in this ? I can take this.

**Comment by bblommers** [comment] 2021-09-17 22:42
That would be very welcome, @rajendersaini! 
The only supported operation is currently `remove` - ideally we support a few more (i.e. `add`/`remove`/`move`/`copy`/`test`)

**Comment by rajendersaini** [comment] 2021-09-18 07:20
https://github.com/spulec/moto/pull/4303. @bblommers  - plz  approve and merge

**Comment by bblommers** [comment] 2021-09-18 20:19
Going to close this, as the provided test case should be working as of moto >= 2.0.9.dev2.
Please let me know if I've missed anything.

**Closed by bblommers** 2021-09-18 20:19 UTC
Labels: enhancement
