### ISSUE TITLE
'DynamoHandler' object has no attribute 'describe_endpoints'

### ISSUE THREAD

**Issue by rickyshelton** [spulec/moto#3714] opened 2021-02-19 16:35 UTC
## 'DynamoHandler' object has no attribute 'describe_endpoints'

Hi,

I'm trying to get a very basic test working, and am encountering the following issue:

`AttributeError: 'DynamoHandler' object has no attribute 'describe_endpoints'`

I can't identify what's wrong, but suspect an environment setup issue. Any help would be greatly appreciated.

### Environment Details:
MacOS Catalina 10.15.7
Setup using pipenv:
`pipenv install moto boto3 pytest`

```
python: v3.7.4
moto: v1.3.16
pytest: v6.2.2
boto3: v1.17.11
botocore: v1.20.11
```

### Example test :
test_moto.py
```
import pytest
from moto import mock_dynamodb2
import boto3

@pytest.fixture
def db_table(scope='session', autouse=True):

    mock = mock_dynamodb2()
    mock.start()
    dynamodb_mock = boto3.client('dynamodb')
    table_name = "table"

    table = dynamodb_mock.create_table(
        AttributeDefinitions=[{"AttributeName": "field_id", "AttributeType": "S"}],
        TableName=table_name,
        KeySchema=[{"AttributeName": "field_id", "KeyType": "HASH"}]
    )

    yield (dynamodb_mock, table_name)
    mock.stop()

def test_write(db_table):
    # do nothing for now
    assert True
```

### Invoked using:
`pytest`

### Full trace attached:
[exception_trace.log](https://github.com/spulec/moto/files/6011425/exception_trace.log)

**Comment by bpandola** [comment] 2021-02-21 02:30
Your test case succeeds for me using the [latest dev version](https://pypi.org/project/moto/1.3.17.dev280/).

**Comment by bblommers** [comment] 2021-02-21 10:20
Looks like you are calling the `describe_endpoints()` somewhere in your setup, it's just not part of the provided test case. 
Moto doesn't support that feature yet, so I'll mark this as an enhancement.

**Comment by rickyshelton** [comment] 2021-02-21 14:45
@bblommers - many thanks for your reply and looking into this.

I don't understand how my test case (which is completely barebones and doesn't do anything apart from create a table) requires new functionality?

Looking here:
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dynamodb/describe-endpoints.html

It looks like this call gives endpoints related to current region - should I be explicitly setting a region this on the boto client setup?

**Comment by bblommers** [comment] 2021-02-21 17:44
Hey @rickyshelton, the test case that you provided doesn't require any new functionality - that already works (for me at least).
The only way I can reproduce the error message/stack trace is by calling the `describe_endpoints()` manually.

**Comment by rickyshelton** [comment] 2021-02-21 20:07
@bblommers - hmm, how strange. I'll keep investigating, including trying the latest dev build as @bpandola has suggested.

**Comment by rickyshelton** [comment] 2021-02-22 09:50
@bblommers @bpandola - I think I have identified the issue.

In my aws config file, I had added the following option to use a new service :

```
[default]
**endpoint_discovery_enabled = true**
output = json
region = eu-west-1
```

I'm assuming this was responsible for call to describe endpoints during the test setup. Commenting out this line makes the test work as expected.

We can probably close this ticket now. Thanks for your help 👍

**Comment by bblommers** [comment] 2021-02-23 08:05
Hi @rickyshelton, thanks for the feedback! I never heard of the `endpoint_discovery_enabled`-configuration option, good to know what that actually does.
The underlying issue (that describe_endpoints() is not implemented) is still there, so we'll close this after that is implemented. 👍

**Closed** 2021-08-28 06:25 UTC
Labels: enhancement
