### ISSUE TITLE
Cognito-idp method initiate_auth: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by bsledz** [spulec/moto#4162] opened 2021-08-11 11:39 UTC
Short reproduction:
```
def cognito_pool_client_id(aws_pool_name, aws_region_name, aws_cognito_client_name, valid_user_credentials):
    with mock_cognitoidp():
        cognito_idp_client = boto3.client('cognito-idp', region_name=aws_region_name)
        result = cognito_idp_client.create_user_pool(
            PoolName=aws_pool_name,
            AliasAttributes=['email'],
            UsernameAttributes=['email'],
        )
        pool_id = result["UserPool"]["Id"]

        username, password = valid_user_credentials
        cognito_idp_client.admin_create_user(
            UserPoolId=pool_id,
            Username=username,
            TemporaryPassword=password
        )

        result = cognito_idp_client.create_user_pool_client(
            UserPoolId=pool_id,
            ClientName=aws_cognito_client_name,
            GenerateSecret=False
        )

        user_auth = cognito_idp_client.initiate_auth(
                ClientId=result["UserPoolClient"]["ClientId"],
                AuthFlow="USER_PASSWORD_AUTH",
                AuthParameters={"USERNAME": username, "PASSWORD": password},
        )

```

Stacktrace:
```
aws_pool_name = 'test_pool', aws_region_name = 'us-east-1', aws_cognito_client_name = 'test_client'
valid_user_credentials = ('valid_user@example.com', 'Password!123')

    @pytest.fixture()
    def cognito_pool_client_id(aws_pool_name, aws_region_name, aws_cognito_client_name, valid_user_credentials):
        with mock_cognitoidp():
            cognito_idp_client = boto3.client('cognito-idp', region_name=aws_region_name)
            result = cognito_idp_client.create_user_pool(
                PoolName=aws_pool_name,
                AliasAttributes=['email'],
                UsernameAttributes=['email'],
            )
            pool_id = result["UserPool"]["Id"]
    
            username, password = valid_user_credentials
            cognito_idp_client.admin_create_user(
                UserPoolId=pool_id,
                Username=username,
                TemporaryPassword=password
            )
    
            result = cognito_idp_client.create_user_pool_client(
                UserPoolId=pool_id,
                ClientName=aws_cognito_client_name,
                GenerateSecret=False
            )
    
>           user_auth = cognito_idp_client.initiate_auth(
                    ClientId=result["UserPoolClient"]["ClientId"],
                    AuthFlow="USER_PASSWORD_AUTH",
                    AuthParameters={"USERNAME": username, "PASSWORD": password},
            )

tests/conftest.py:55: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../venv/lib/python3.8/site-packages/botocore/client.py:316: in _api_call
    return self._make_api_call(operation_name, kwargs)
../venv/lib/python3.8/site-packages/botocore/client.py:612: in _make_api_call
    http, parsed_response = self._make_request(
../venv/lib/python3.8/site-packages/botocore/client.py:632: in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
../venv/lib/python3.8/site-packages/botocore/endpoint.py:102: in make_request
    return self._send_request(request_dict, operation_model)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = cognito-idp(https://cognito-idp.us-east-1.amazonaws.com)
request_dict = {'body': b'{"ClientId": "datj2vvb76wy485gadpaflvjnk", "AuthFlow": "USER_PASSWORD_AUTH", "AuthParameters": {"USERNAME":...59-generic Botocore/1.15.49', 'X-Amz-Target': 'AWSCognitoIdentityProviderService.InitiateAuth'}, 'method': 'POST', ...}
operation_model = OperationModel(name=InitiateAuth)

    def _send_request(self, request_dict, operation_model):
        attempts = 1
        request = self.create_request(request_dict, operation_model)
        context = request_dict['context']
        success_response, exception = self._get_response(
            request, operation_model, context)
        while self._needs_retry(attempts, operation_model, request_dict,
                                success_response, exception):
            attempts += 1
            # If there is a stream associated with the request, we need
            # to reset it before attempting to send the request again.
            # This will ensure that we resend the entire contents of the
            # body.
            request.reset_stream()
            # Create a new request when retried (including a new signature).
            request = self.create_request(
                request_dict, operation_model)
            success_response, exception = self._get_response(
                request, operation_model, context)
        if success_response is not None and \
>               'ResponseMetadata' in success_response[1]:
E               TypeError: argument of type 'NoneType' is not iterable

../venv/lib/python3.8/site-packages/botocore/endpoint.py:150: TypeError
```

**Comment by bblommers** [comment] 2021-08-11 12:28
Thanks for raising this @bsledz. Looks like we're not supporting the `USER_PASSWORD_AUTH`-flow at the moment, so I'll mark this as an enhancement to implement that.

The only flows we currently do support (as of moto 2.2.2) for `initiate_auth` is `USER_SRP_AUTH` and `REFRESH_TOKEN`.

**Comment by bsledz** [comment] 2021-08-11 13:57
@bblommers Thank you! I suggested change, please take a look.

**Comment by bblommers** [comment] 2021-08-29 19:27
This is now fixed as of Moto >= 2.2.3, so I'll close this.
Let us know if there's anything else missing.

**Closed by bblommers** 2021-08-29 19:27 UTC
Labels: enhancement

**Comment by JamieMcKernanKaizen** [comment] 2021-11-22 11:32
@bblommers I am getting this exact issue in moto version 2.2.16 - it may have been re-introduced perhaps?

**Comment by bblommers** [comment] 2021-11-22 13:46
The test from the OP still passes in master, so it looks like you're running into a different bug @JamieMcKernanKaizen . Feel free to open a new issue, ideally with a reproducible test, and we'll look into it.

**Comment by JamieMcKernanKaizen** [comment] 2021-11-23 10:19
> The test from the OP still passes in master, so it looks like you're running into a different bug @JamieMcKernanKaizen . Feel free to open a new issue, ideally with a reproducible test, and we'll look into it.

Opened new issue here #4623
