### ISSUE TITLE
Using `mock_s3` breaks instance IAM permissions

### ISSUE THREAD

**Issue by kawa-marcin** [spulec/moto#1731] opened 2018-07-23 13:36 UTC
Tests run automatically on the AWS instance. Some tests are mocking the S3 service but some of them are actually downloading some test related assets from AWS bucket.

If there are any tests with `mock_s3` used before accessing the AWS bucket, IAM permission for instance won't work and traceback will be printed:

```python
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/venv/local/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
```

Though there is **no** AWS related environment variables or `~/.aws/credentials` available as instance itself has IAM role assigned for accessing required buckets.

In tests I use the `mock_s3` like that:

```python
class Test(unittest.TestCase):
    def setUp(self):
        self.mock_s3 = mock_s3()
        self.mock_s3.start()

    def tearDown(self):
        self.mock_s3.stop()

    def test_something(self):
        cli = boto3.client('s3', config=Config(signature_version='s3v4'))
        .create_bucket(Bucket='foobar')
```

---

Everything works as expected if I change the order of tests and the ones with real S3 calls are executed before tests where S3 service is mocked.

Any thoughts / workarounds you have in mind?

---

```python
# requirements.txt

moto==1.3.3
boto3==1.7.26
```

**Comment by jsmith** [comment] 2018-09-20 19:00
I'm receiving the same issue while running tests using `moto` on an EC2 instance using an IAM Role.

**Test file**
```python
# test.py
import moto
import boto3

@moto.mock_s3
def test_a():
    s3 = boto3.client('s3')  # if you comment this out, the tests will pass

def test_b():
    s3 = boto3.resource('s3')
    b = s3.Bucket('some-bucket')
    b.download_file('some-key', '/some/path')
```

**Command**
```
pytest test.py
```

**Versions**
```
boto3==1.7.60
botocore==1.10.60
moto==1.3.5
```

**Comment by spulec** [comment] 2018-09-22 21:05
I believe this is a dupe of https://github.com/spulec/moto/issues/1793. Let me know if not.

**Closed by spulec** 2018-09-22 21:05 UTC
