### ISSUE TITLE
S3 multipart upload completion error

### ISSUE THREAD

**Issue by JonWhitehead** [spulec/moto#1513] opened 2018-03-15 01:18 UTC
I have been trying to run the Multipart upload example against Moto from:
https://docs.aws.amazon.com/AmazonS3/latest/dev/llJavaUploadFile.html
Using the class UploadObjectMPULowLevelAPI.

When calling completeMultipartUpload, I get an error response:

com.amazonaws.services.s3.model.AmazonS3Exception: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag. (Service: Amazon S3; Status Code: 400; Error Code: InvalidPart; Request ID: null; S3 Extended Request ID: null), S3 Extended Request ID: null

I believe the error is being thrown from the below code:

s3/models.py

    def complete(self, body):
        decode_hex = codecs.getdecoder("hex_codec")
        total = bytearray()
        md5s = bytearray()

        last = None
        count = 0
        for pn, etag in body:
            part = self.parts.get(pn)
            if part is None or part.etag != etag:
                raise InvalidPart()
                

The part.etag appears to contain a string with additional quotes e.g '"7319d066c5e41e4c25f3fc3cef366adb"' They are being removed on line 175, however I think they are causing the prior equality check on line 171 to fail.

The addtional quotes are introduced in FakeKey, line 97: return '"{0}"'.format(self._etag)
https://github.com/spulec/moto/blob/master/moto/s3/models.py#L97

Removing the outer quotes appears to fix the issue e.g return "{0}".format(self._etag)
I'm not sure whether this is an appropriate fix, it would be great it someone could take a look.
Thanks in advance.
Jon

**Comment by bwidmeier** [comment] 2018-03-21 16:51
I am also running into this issue. Anyone have any thoughts on this?

**Comment by avizana** [comment] 2018-03-22 07:10
I removed the outer quotes as well and everything is working just fine for me.

**Comment by galvinograd** [comment] 2018-04-03 13:23
+1

**Comment by spulec** [comment] 2018-04-12 23:06
Can one of your add a minimum failing test case? We have multiple tests that do multipart uploads so it would be helpful to understand what is different.

**Comment by avizana** [comment] 2018-04-15 05:05
I just used the multipart upload example from AWS site:

        AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("some-kind-of-endpoint"))
                .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials("user", "pass")))
                .disableChunkedEncoding()
                .withPathStyleAccessEnabled(true)
                .build();

        // Create a list of UploadPartResponse objects. You get one of these
        // for each part upload.
        List<PartETag> partETags = new ArrayList<PartETag>();

        // Step 1: Initialize.
        InitiateMultipartUploadRequest initRequest = new
                InitiateMultipartUploadRequest("bucket", "key");
        InitiateMultipartUploadResult initResponse =
                s3Client.initiateMultipartUpload(initRequest);

        File file = new File("filepath");
        long contentLength = file.length();
        long partSize = 5242880; // Set part size to 5 MB.

        try {
            // Step 2: Upload parts.
            long filePosition = 0;
            for (int i = 1; filePosition < contentLength; i++) {
                // Last part can be less than 5 MB. Adjust part size.
                partSize = Math.min(partSize, (contentLength - filePosition));

                // Create request to upload a part.
                UploadPartRequest uploadRequest = new UploadPartRequest()
                        .withBucketName("bucket").withKey("key")
                        .withUploadId(initResponse.getUploadId()).withPartNumber(i)
                        .withFileOffset(filePosition)
                        .withFile(file)
                        .withPartSize(partSize);

                // Upload part and add response to our list.
                partETags.add(
                        s3Client.uploadPart(uploadRequest).getPartETag());

                filePosition += partSize;
            }

            // Step 3: Complete.
            CompleteMultipartUploadRequest compRequest = new
                    CompleteMultipartUploadRequest(
                    "bucket",
                    "key",
                    initResponse.getUploadId(),
                    partETags);

            s3Client.completeMultipartUpload(compRequest);
        } catch (Exception e) {
            s3Client.abortMultipartUpload(new AbortMultipartUploadRequest(
                    "bucket", "key", initResponse.getUploadId()));
        }

**Comment by jonaskint** [comment] 2018-05-08 08:39
@spulec is there something expected for this issue to move forward?

**Comment by bwidmeier** [comment] 2018-05-08 14:14
I don't remember where I read this, but I believe someone thought this issue was specific to multipart uploads using the Java SDK. Maybe it uses etags without quotes, but the other major SDKs do use quotes?

**Comment by wonko** [comment] 2018-05-28 17:53
Provided a fix that works for us in https://github.com/spulec/moto/pull/1651 Our test case as the simple example from Evaporate.JS.

**Comment by spulec** [comment] 2018-07-19 14:06
Can someone test this again now that we've merged https://github.com/spulec/moto/pull/1707 and see if we can close this?

**Comment by OJFord** [comment] 2018-09-04 11:28
AWS ETags have the form `"<MD5>"` (multipart `"<MD5>-<num_parts>"`) - i.e. the quotes are included, like `{..., 'ETag': '"..."'}` response.

**Comment by xiehf319** [comment] 2018-12-20 11:51
I have been trying  multipart upload inputstream, because  i can't know the total size;

env:

spring boot 2.0
```    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-s3</artifactId>
      <version>1.11.336</version>
    </dependency>
```

code:

step 1.  loop call below method:

```
public void partUpload(String bucketName,
                           String fileKey,
                           byte[] bytes,
                           int partNumber, boolean isLastPart) {
        ByteArrayInputStream inputStream = new ByteArrayInputStream(bytes);
            InitiateMultipartUploadRequest initRequest = new InitiateMultipartUploadRequest(bucketName, fileKey);
            InitiateMultipartUploadResult initResponse = s3Client.initiateMultipartUpload(initRequest);
           
 UploadPartRequest uploadRequest = new UploadPartRequest()
                    .withBucketName(bucketName)
                    .withKey(fileKey)
                    .withUploadId(initResponse.getUploadId())
                    .withPartNumber(partNumber)
                    .withInputStream(inputStream)
                    .withLastPart(isLastPart)
                    .withPartSize(bytes.length);
            // Upload the part and add the response's ETag to our list.
            UploadPartResult uploadResult = s3Client.uploadPart(uploadRequest);
            PartETag partETag = uploadResult.getPartETag();
           // .... .use redis  to save the PartETag as a list
}

```
step 2. when the stream end, call below method

```

// .......get PartETaglist from redis
CompleteMultipartUploadRequest compRequest =
                        new CompleteMultipartUploadRequest(partUploadDto.getBucketName(), fileKey,
                                partUploadDto.getUploadId(),
                                eTags);
                s3Client.completeMultipartUpload(compRequest);
```

Q: 
1. when just one PartETag it works success;
2. where PartETag size is more then one, it will throw exception, as below : 
`
com.amazonaws.services.s3.model.AmazonS3Exception: One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.
`

**Comment by xiehf319** [comment] 2018-12-21 02:06
i solved it,  because every part , the uploadId is difference , i save the first uploadId with redis, then next part i use the previous uploadId from redis.  then success.

**Comment by mastagino** [comment] 2019-08-30 02:39
Just to let you guys know, if you add this in your CORS bucket configuration, it might solve your issue. For me, it did:
<ExposeHeader>ETag</ExposeHeader>

**Comment by elgatovielma** [comment] 2019-09-10 13:48
> i solved it, because every part , the uploadId is difference , i save the first uploadId with redis, then next part i use the previous uploadId from redis. then success.

Could you please pass the code you used to solve the issue, please? I think I have the same problem.

**Comment by sureshavm** [comment] 2020-07-02 03:23
Facing the similar error, could someone shed light here for the fix or how to over come?

`com.amazonaws.services.s3.model.AmazonS3Exception: One or more of the specified parts could not be found. The part may not have been uploaded`

**Comment by bblommers** [comment] 2020-07-02 06:08
Hi @sureshavm, can you share your test case?
Which version of Moto are you using?

**Comment by KhushbuAgr** [comment] 2020-07-03 11:58
@bblommers - we are reading the source which has around 200 files and each is approx of 450 MB. the count is **352172008**.  After this, we are joining with 2 other tables and store the result in a Dataframe. Dataframe count shows  **352172008**. But when we are writing dataframe output in the S3 file, records are getting lost and the count is coming approx **335751188**. Each time count is varying but mostly close to 335751188.
 ```
The job as such doesnt fail but we could see failed tasks in yarn logs and the error message is 
Caused by: com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.model.AmazonS3Exception: One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag. (Service: Amazon S3; Status Code: 400; Error Code: InvalidPart; Request ID: C89D6E84D98B1642; S3 Extended Request ID: mqSAvwyerL/xYelXkqfG6uV/8RzwS6iwTsYkuOTi+/NDc6dpZZZLvHfUAjdA4UukjmES7TrvPjQ=), S3 Extended Request ID: mqSAvwyerL/xYelXkqfG6uV/8RzwS6iwTsYkuOTi+/NDc6dpZZZLvHfUAjdA4UukjmES7TrvPjQ=
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
```

**Comment by bblommers** [comment] 2022-05-28 10:16
Apologies for the delay @KhushbuAgr - this one must have slipped through.
In order to have a look at this, I'd need something reproducible though. If you have an example repro that showcases this issue, that would be ideal.

**Closed** 2022-08-20 11:04 UTC
Labels: bug
