### ISSUE TITLE
Using StreamingBody as a file fails with GzipFile

### ISSUE THREAD

**Issue by jruere** [spulec/moto#1603] opened 2018-04-27 20:38 UTC
The following code fails:

```python
s3 = boto3.resource('s3', region_name='us-east-1')
s3.create_bucket(Bucket='test-bucket')
obj = s3.Object('test-bucket', 'an-object')
obj.put(Body=io.BytesIO(gzip.compress(b'some data')))

gzip.GzipFile(fileobj=s3.Object('test-bucket', 'an-object').get()['Body'], mode='rb').read()
```

The traceback is:

```
Traceback (most recent call last):
  File "/home/javier/tmp/virtualenvs-2/lupin-analytics/lib/python3.5/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/home/javier/Projects/domainsbot.com/lupin-analytics/tests/lupin_analytics_/test_repositories.py", line 377, in test_moto
    gzip.GzipFile(fileobj=s3.Object('test-bucket', 'an-object').get()['Body'], mode='rb').read()
  File "/usr/lib64/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib64/python3.5/gzip.py", line 461, in read
    if not self._read_gzip_header():
  File "/usr/lib64/python3.5/gzip.py", line 404, in _read_gzip_header
    magic = self._fp.read(2)
  File "/usr/lib64/python3.5/gzip.py", line 82, in read
    return self.file.read(size)
  File "/home/javier/tmp/virtualenvs-2/lupin-analytics/lib/python3.5/site-packages/botocore/response.py", line 74, in read
    chunk = self._raw_stream.read(amt)
  File "/home/javier/tmp/virtualenvs-2/lupin-analytics/lib/python3.5/site-packages/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
ValueError: I/O operation on closed file.
```

The code works if the last line is changed to:

```python
gzip.GzipFile(fileobj=io.BytesIO(s3.Object('test-bucket', 'an-object').get()['Body'].read()), mode='rb').read()
```

Of course, it also works with boto3 without reading into memory.

I'm using moto 1.3.3. I tried this with boto3 1.5.1 and 1.7.10.

**Comment by spulec** [comment] 2018-06-01 01:38
My first guess is to do with us either not setting the content-encoding right or the content-length being incorrect.

Either way, seems like we need to fix something so I'm going to mark this as a bug.

**Comment by jrideout** [comment] 2018-10-01 03:55
I think this is due to: https://github.com/urllib3/urllib3/issues/1305

**Comment by vbarbaresi** [comment] 2021-10-29 21:34
This seems fixed: I can't reproduce with moto on _master_ and `urllib3==1.26.7`

**Comment by bblommers** [comment] 2021-10-30 10:14
Thanks for  checking @vbarbaresi. I'll close this, but do let us know if the issue still persists @jruere.

**Closed by bblommers** 2021-10-30 10:14 UTC
Labels: bug

**Comment by jruere** [comment] 2021-11-01 08:33
Thanks!
