### ISSUE TITLE
DockerException in batch model - Error while fetching server API version

### ISSUE THREAD

**Issue by dazza-codes** [spulec/moto#3517] opened 2020-12-04 01:41 UTC
This might be a bug somewhere in the python docker package or it might be fixed upstream but moto[server] could use an update to any pinned dependency?

- https://github.com/docker/docker-py/issues/2717

```
    
>       self.docker_client = docker.from_env()

/opt/conda/envs/project/lib/python3.7/site-packages/moto/batch/models.py:345: 

...

self = <docker.api.client.APIClient object at 0x7f8b52ceec90>

    def _retrieve_server_version(self):
        try:
            return self.version(api_version=False)["ApiVersion"]
        except KeyError:
            raise DockerException(
                'Invalid response from docker daemon: key "ApiVersion"'
                ' is missing.'
            )
        except Exception as e:
            raise DockerException(
>               'Error while fetching server API version: {0}'.format(e)
            )
E           docker.errors.DockerException: Error while fetching server API version: cannot unpack non-iterable CallbackResponse object

/opt/conda/envs/project/lib/python3.7/site-packages/docker/api/client.py:222: DockerException

```

### versions

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

$ docker --version
Docker version 19.03.14, build 5eb3275d40

$ service docker status
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-12-03 16:13:07 PST; 1h 26min ago
     Docs: https://docs.docker.com
 Main PID: 1844 (dockerd)
    Tasks: 10
   CGroup: /system.slice/docker.service
           └─1844 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

$ python --version
Python 3.7.8

$ poetry --version
Poetry version 1.1.4

$ poetry show docker
name         : docker
version      : 4.4.0
description  : A Python library for the Docker Engine API.

dependencies
 - pywin32 227
 - requests >=2.14.2,<2.18.0 || >2.18.0
 - six >=1.4.0
 - websocket-client >=0.32.0

$ poetry show moto
name         : moto
version      : 1.3.16
description  : A library that allows your python tests to easily mock out the boto library

dependencies
 - aws-xray-sdk >=0.93,<0.96 || >0.96
 - boto >=2.36.0
 - boto3 >=1.9.201
 - botocore >=1.12.201
 - cfn-lint >=0.4.0
 - cryptography >=2.3.0
 - docker >=2.5.1
 - ecdsa <0.15
 - flask *
 - idna >=2.5,<3
 - Jinja2 >=2.10.1
 - jsondiff >=1.1.2
 - MarkupSafe <2.0
 - mock *
 - more-itertools *
 - python-dateutil >=2.1,<3.0.0
 - python-jose >=3.1.0,<4.0.0
 - pytz *
 - PyYAML >=5.1
 - requests >=2.5
 - responses >=0.9.0
 - six >1.9
 - werkzeug *
 - xmltodict *
 - zipp *
```

**Comment by bblommers** [comment] 2020-12-04 09:02
Hi @dazza-codes, thanks for raising this.
Is it possible to upgrade moto to 1.3.16.dev110 (or higher)? There was another Docker-bug (#3359) that was fixed in that release, I wonder if it's related.

**Comment by sclothie** [comment] 2020-12-08 21:25
FWIW, I'm getting a similar error when trying to invoke a lambda and I am using `1.3.16.dev110`.

**Comment by maxwellchandler** [comment] 2020-12-30 18:09
FWIW, I'm getting a similar error when trying to invoke a lambda and I am using 1.3.16.dev110.

**Comment by bblommers** [comment] 2021-01-07 16:07
@sclothie @maxwellchandler 
Are you getting a similar error, or the exact same? Please give the exact error if it's different from the original post.
A list of dependencies/versions in your project (like in the original post) would be useful as well.

**Comment by sclothie** [comment] 2021-01-07 18:25
The error I get is similar: `error running docker: Error while fetching server API version: 'CallbackResponse' object is not iterable.` It appears in the body of the response payload when I do an async lambda invocation. 

My dependencies:
```aiohttp==3.7.2
appdirs==1.4.4
astroid==2.4.2
async-timeout==3.0.1
attrs==20.3.0
aws-sam-translator==1.29.0
aws-xray-sdk==2.6.0
black==19.10b0
boto==2.49.0
boto3==1.12.49
botocore==1.15.49
certifi==2020.11.8
cffi==1.14.3
cfn-lint==0.40.0
chardet==3.0.4
click==7.1.2
cryptography==3.2.1
dataclasses==0.8
decorator==4.4.2
defusedxml==0.6.0
docker==4.4.0
docutils==0.15.2
ecdsa==0.14.1
freezegun==0.3.12
future==0.18.2
gql==3.0.0a4
graphql-core==3.1.2
idna==2.8
idna-ssl==1.1.0
importlib-metadata==2.0.0
importlib-resources==1.5.0
indigoag.devops.common==0.15.0
influxdb-client==1.12.0
isort==4.3.21
Jinja2==2.11.2
jira==2.0.0
jmespath==0.10.0
jsondiff==1.1.2
jsonpatch==1.26
jsonpickle==1.4.1
jsonpointer==2.0
jsonschema==3.2.0
junit-xml==1.9
lazy-object-proxy==1.4.3
MarkupSafe==1.1.1
mccabe==0.6.1
mock==4.0.2
more-itertools==8.6.0
moto==1.3.16.dev110
multidict==5.0.2
mypy==0.790
mypy-extensions==0.4.3
networkx==2.5
oauthlib==3.1.0
packaging==20.4
pathspec==0.8.1
pbr==5.5.1
pdpyras==4.1.2
pluggy==0.13.1
py==1.9.0
pyasn1==0.4.8
pycparser==2.20
PyGithub==1.53
PyJWT==1.7.1
pylint==2.5.3
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==5.4.3
pytest-custom-exit-code==0.3.0
pytest-mock==3.3.1
pytest-socket==0.3.4
python-dateutil==2.8.1
python-jose==3.2.0
pytz==2020.4
PyYAML==5.3.1
regex==2020.11.13
requests==2.25.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
responses==0.12.1
rsa==4.6
Rx==3.1.1
s3transfer==0.3.3
six==1.15.0
slack-sdk==3.0.0
sshpubkeys==3.1.0
toml==0.10.2
typed-ast==1.4.1
typing-extensions==3.7.4.3
urllib3==1.25.11
wcwidth==0.2.5
websocket-client==0.57.0
Werkzeug==1.0.1
wrapt==1.12.1
xmltodict==0.12.0
yarl==1.5.1
zipp==3.4.0

**Comment by maxwellchandler** [comment] 2021-01-07 21:51
I am getting the exact same error as the original post to clarify.

**Comment by bblommers** [comment] 2021-01-09 11:25
I'm unable to reproduce this I'm afraid. I can reproduce it with moto==1.3.16.dev96, but not with 1.3.16.dev110.

Regardless: I've only seen this error when docker is not running. I'm guessing that `docker info` will also fail?

**Comment by maxwellchandler** [comment] 2021-01-10 19:20
I have docker running and `docker info` does not fail. Also using 1.3.16.dev110 on osx. Getting the error on a `create_function` command.

**Comment by maxwellchandler** [comment] 2021-01-10 21:21
If it helps I could post the exact test.

**Comment by bblommers** [comment] 2021-01-11 12:55
That would be helpful, yes. Thanks

**Comment by maxwellchandler** [comment] 2021-01-11 21:39
`"""Unit testing for AWS Lambda"""

import json
import uuid
import boto3
import os
from moto.awslambda import mock_lambda
from moto.sts import mock_sts
from moto.iam import mock_iam


@mock_sts
@mock_iam
@mock_lambda
def test_invoke():
    os.environ["AWS_ACCESS_KEY_ID"] = "testing"
    os.environ["AWS_SECRET_ACCESS_KEY"] = "testing"
    os.environ["AWS_SECURITY_TOKEN"] = "testing"
    os.environ["AWS_SESSION_TOKEN"] = "testing"
    os.environ["AWS_DEFAULT_REGION"] = "us-east-2"
    #AWS_FAKE_ENDPOINT = 'http://0.0.0.0:5000/'
    from baotools.serverless import Lambda

    """
    Unit test for method 'invoke_function'
    """

    CLIENT_IAM = boto3.client("iam",
                              #endpoint_url=AWS_FAKE_ENDPOINT
                              )
    CLIENT_LAMBDA = boto3.client("lambda"
                                 #,endpoint_url=AWS_FAKE_ENDPOINT
                                 )
    """
    Fixture for the creation and the deletion of a Lambda function.
    """
    # Generate a random function name (with prefix 'pytest.')
    function_name = "pytest_" + str(uuid.uuid4())

    # Create a role that allows us to manage Lambda (prefixed similarly)
    role_name = "pytest." + str(uuid.uuid4())

    # Policy Document for Trust Relationship for Lambda Basic Execution Role
    policy_trust = {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {"Service": "lambda.amazonaws.com"},
                "Action": "sts:AssumeRole",
            }
        ],
    }
    # Role creation
    response = CLIENT_IAM.create_role(
        RoleName=role_name, AssumeRolePolicyDocument=json.dumps(policy_trust)
    )

    role_arn = response["Role"]["Arn"]

    # Attach AdministratorAccess policy to the created role
    _policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
    CLIENT_IAM.attach_role_policy(RoleName=role_name, PolicyArn=_policy_arn)

    script_dir = os.path.dirname(__file__)  # <-- absolute dir the script is in
    rel_path = "serverless_helloworld.zip"
    abs_file_path = os.path.join(script_dir, rel_path)

    CLIENT_LAMBDA.create_function(
        FunctionName=function_name,
        Runtime="python3.8",
        Role=role_arn,
        Handler="serverless_helloworld.lambda_handler",
        Code={"ZipFile": open(abs_file_path, "rb").read(),},
    )

    payload = {"param": "Hello world"}
    payload_bytes = json.dumps(payload).encode("utf-8")

    _kwargs = {
        "FunctionName": function_name,
        "InvocationType": 'RequestResponse',
        "Payload": payload_bytes,
    }

    response = CLIENT_LAMBDA.invoke(**_kwargs, Qualifier="$LATEST")

   
    assert json.loads(response["Payload"].read()) == payload["param"]
`

**Comment by maxwellchandler** [comment] 2021-01-11 21:45
[serverless_helloworld.zip](https://github.com/spulec/moto/files/5798470/serverless_helloworld.zip)

**Comment by bblommers** [comment] 2021-01-12 14:33
Thanks for providing the test, @maxwellchandler.
Looks like it was only fixed in 1.3.16.dev122 instead. That release contains #3466, a fix for a downstream change in the Responses-library. No idea why that would affect Docker though.. 

Proof:
https://github.com/bblommers/testdockerexception/runs/1688643905?check_suite_focus=true

That repo contains the test you provided, and runs it against various moto-versions.
Note that the OSX-test always fails, because Github does not have Docker installed on their OSX machines.

**Comment by maxwellchandler** [comment] 2021-01-12 16:49
Thanks so much for the quick response! I am not sure where I am going wrong but the `dev122` version on macosx fails here https://github.com/bblommers/testdockerexception/runs/1688643905?check_suite_focus=true with a different error than I am getting when I exit all docker processes. In the link we get `error running docker: Error while fetching server API version` and this is because it doesnt have docker installed, however when I quit all docker processes and run the same test on my local machine I still get the original error. I am also getting the same original error even with `dev122`. I wonder if I am doing something wrong with docker? Or perhaps its an osx issue... All I do before running the test is start docker desktop and verify its running with `docker info`.

**Comment by bblommers** [comment] 2021-01-12 17:15
Connecting to Docker from a Mac does seem to be slightly more difficult, looking at this:  https://stackoverflow.com/questions/34256645/connecting-to-docker-machine-via-docker-py-on-osx

I don't have access to an OSX machine though, so I can't try any of these solutions unfortunately

**Comment by bblommers** [comment] 2021-10-16 22:26
As far as I can tell, all bugs surrounding Docker-versions have been fixed for now, so I'll close this.
Let me know if I've missed anything.

**Closed by bblommers** 2021-10-16 22:26 UTC
Labels: bug
