### ISSUE TITLE
NotImplemented: S3: select_object_content

### ISSUE THREAD

**Issue by CodyConstine** [spulec/moto#3487] opened 2020-11-20 14:43 UTC
When using moto to mock s3 for the following call:
```
response = self.s3.select_object_content(
            Bucket="bucket",
            Key="a_csv_file.csv",
            Expression="SELECT * FROM S3Object s LIMIT 1",
            ExpressionType="SQL",
            InputSerialization={"CSV": {"FileHeaderInfo": "USE"}},
            OutputSerialization={"JSON": {}}
        )
```

I get the following exception:
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
data_ingester.py:83: in get_file_schema
    OutputSerialization={"JSON": {}}
venv/lib/python3.7/site-packages/botocore/client.py:357: in _api_call
    return self._make_api_call(operation_name, kwargs)
venv/lib/python3.7/site-packages/botocore/client.py:663: in _make_api_call
    operation_model, request_dict, request_context)
venv/lib/python3.7/site-packages/botocore/client.py:682: in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
venv/lib/python3.7/site-packages/botocore/endpoint.py:102: in make_request
    return self._send_request(request_dict, operation_model)
venv/lib/python3.7/site-packages/botocore/endpoint.py:137: in _send_request
    success_response, exception):
venv/lib/python3.7/site-packages/botocore/endpoint.py:256: in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
venv/lib/python3.7/site-packages/botocore/hooks.py:356: in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
venv/lib/python3.7/site-packages/botocore/hooks.py:228: in emit
    return self._emit(event_name, kwargs)
venv/lib/python3.7/site-packages/botocore/hooks.py:211: in _emit
    response = handler(**kwargs)
venv/lib/python3.7/site-packages/botocore/retryhandler.py:183: in __call__
    if self._checker(attempts, response, caught_exception):
venv/lib/python3.7/site-packages/botocore/retryhandler.py:251: in __call__
    caught_exception)
venv/lib/python3.7/site-packages/botocore/retryhandler.py:269: in _should_retry
    return self._checker(attempt_number, response, caught_exception)
venv/lib/python3.7/site-packages/botocore/retryhandler.py:317: in __call__
    caught_exception)
venv/lib/python3.7/site-packages/botocore/retryhandler.py:223: in __call__
    attempt_number, caught_exception)
venv/lib/python3.7/site-packages/botocore/retryhandler.py:359: in _check_caught_exception
    raise caught_exception
venv/lib/python3.7/site-packages/botocore/endpoint.py:197: in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
venv/lib/python3.7/site-packages/botocore/hooks.py:356: in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
venv/lib/python3.7/site-packages/botocore/hooks.py:228: in emit
    return self._emit(event_name, kwargs)
venv/lib/python3.7/site-packages/botocore/hooks.py:211: in _emit
    response = handler(**kwargs)
venv/lib/python3.7/site-packages/moto/core/models.py:323: in __call__
    request, request.url, request.headers
venv/lib/python3.7/site-packages/moto/s3/responses.py:958: in key_or_control_response
    response = self._key_response(request, full_url, headers)
venv/lib/python3.7/site-packages/moto/s3/responses.py:1122: in _key_response
    return self._key_response_post(request, body, bucket_name, query, key_name)
venv/lib/python3.7/site-packages/moto/s3/responses.py:1654: in _key_response_post
    self._set_action("KEY", "POST", query)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <moto.s3.responses.ResponseObject object at 0x11e4d80d0>
action_resource_type = 'KEY', method = 'POST'
querystring = {'select': [''], 'select-type': ['2']}

    def _set_action(self, action_resource_type, method, querystring):
        action_set = False
        for action_in_querystring, action in ACTION_MAP[action_resource_type][
            method
        ].items():
            if action_in_querystring in querystring:
                self.data["Action"] = action
                action_set = True
        if not action_set:
>           self.data["Action"] = ACTION_MAP[action_resource_type][method]["DEFAULT"]
E           KeyError: 'DEFAULT'

venv/lib/python3.7/site-packages/moto/s3/responses.py:524: KeyError
```

The exact same call on a real s3 bucket produces the correct results as documented here:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.select_object_content

I tried csv, json, and parquet file formats and the all failed in moto and passed on real s3. I also tried different OutputSerializations.

Packages all installed from pip:
```
boto3==1.15.18
botocore==1.18.18
moto==1.3.16
```

**Comment by bblommers** [comment] 2020-11-21 11:21
Hi @CodyConstine, that feature isn't implemented yet I'm afraid.

Will mark it as an enhancement.

**Comment by bblommers** [comment] 2020-12-05 11:07
This is a duplicate of #3301. I'll close this, considering there's already some discussion in that issue.

**Closed by bblommers** 2020-12-05 11:07 UTC
Labels: enhancement
