### ISSUE TITLE
sts mock doesn't stop properly

### ISSUE THREAD

**Issue by araker** [spulec/moto#5452] opened 2022-09-07 15:57 UTC
Hello, 

I have the following test script. 
 
`
from moto import mock_sts
import boto3

_sts_mock = mock_sts()
_sts_mock.start()

account_id = boto3.client("sts").get_caller_identity().get("Account")
print(account_id) --result 123456789012

_sts_mock.stop()

boto3.client("sts").get_caller_identity().get("Account")
print(account_id) --result 123456789012

import boto3 as boto
boto.client("sts").get_caller_identity().get("Account")
print(account_id) --result 123456789012
`

What I expect is that after the '_sts_mock.stop()' call the next call to Sts would return a actual aws account id (not the fake moto one) Even when importing boto3 again the mocked account id is still returned. 

So should sts revert back to it's original behavior after the mock is stopped? 

When stopping other mocks (like s3) the behavior of boto3 is reverted back as expected. 

Moto version 4.0.1 
Boto3 version 1.24.50

**Comment by bblommers** [comment] 2022-09-07 16:23
That is the expected behaviour @araker. As long as _a_ mock is active, we intercept all calls to AWS regardless of the target service.
The purpose of this is safety, to ensure that a test does not accidentally call AWS (and potentially create some expensive resources) just because the developer forgot to enable all of the relevant mocks.

There are some similar requests, to allow Moto to be more flexible in which calls are intercepted and which ones are not, but nothing implemented yet. (e.g. #4597)

**Comment by araker** [comment] 2022-09-07 18:21
@bblommers , just to be crystal clear here, I'm stopping the mock explicitly, but the behavior of the mock still continues and that is epected behavior?

**Comment by araker** [comment] 2022-09-12 12:38
@bblommers , just to clarify. are you presuming here that another mock is still active and that that's the reason why the sts mock is still active? In this environment the only active mock is the sts one. 

So when

**Comment by bblommers** [comment] 2022-09-12 18:29
> @bblommers , just to clarify. are you presuming here that another mock is still active and that that's the reason why the sts mock is still active? In this case the only active mock is the sts one.
> 

That was my assumption, yes, because you said `When stopping other mocks (like s3)` - it sounded like you had multiple mocks active at the same time.

I'm not able to reproduce this though - the example above gives me an error that `The security token included in the request is invalid.` after the mock is stopped, as expected.

Are you able to create a repo with a CI/CD that showcases this behaviour? Maybe there's an environment-specific issue that's stopping me from reproducing this.

**Comment by bblommers** [comment] 2022-10-07 10:08
Without a repro there's not much we can do, so I'll close this.

**Closed by bblommers** 2022-10-07 10:08 UTC
Labels: question
