### ISSUE TITLE
Moto 3.0.2 seems to be incompatible with Python 3.9 typing

### ISSUE THREAD

**Issue by adammacudzinski** [spulec/moto#4829] opened 2022-02-04 16:42 UTC
Greetings, we are in the process of migrating our Python codebase to Python 3.9 and one of the first tests that broke after this change was a test that featured the `@mock_s3` decorator. Here is the associated stack trace:

File "/usr/local/lib/python3.9/dist-packages/moto/__init__.py", line 17, in f
    module = importlib.import_module(module_name, "moto")
  File "/home/luminar/mambaforge/envs/dei_env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/dist-packages/moto/s3/__init__.py", line 1, in <module>
    from .models import s3_backend
  File "/usr/local/lib/python3.9/dist-packages/moto/s3/models.py", line 20, in <module>
    from moto.core import (
  File "/usr/local/lib/python3.9/dist-packages/moto/core/__init__.py", line 1, in <module>
    from .models import BaseModel, BaseBackend, moto_api_backend, ACCOUNT_ID  # noqa
  File "/usr/local/lib/python3.9/dist-packages/moto/core/models.py", line 23, in <module>
    from .custom_responses_mock import (
  File "/usr/local/lib/python3.9/dist-packages/moto/core/custom_responses_mock.py", line 6, in <module>
    from werkzeug.wrappers import Request
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/__init__.py", line 2, in <module>
    from .test import Client as Client
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/test.py", line 20, in <module>
    from .datastructures import Authorization
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/datastructures.py", line 3059, in <module>
    from . import http
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/http.py", line 395, in <module>
    ) -> t.Union[t.Tuple[str, t.Dict[str, str]], t.Tuple[t.Any, ...]]:
  File "/home/luminar/mambaforge/envs/dei_env/lib/python3.9/typing.py", line 277, in inner
    return func(*args, **kwds)
  File "/home/luminar/mambaforge/envs/dei_env/lib/python3.9/typing.py", line 354, in __getitem__
    return self._getitem(self, parameters)
  File "/home/luminar/mambaforge/envs/dei_env/lib/python3.9/typing.py", line 467, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/home/luminar/mambaforge/envs/dei_env/lib/python3.9/typing.py", line 246, in _remove_dups_flatten
    return tuple(_deduplicate(params))
  File "/home/luminar/mambaforge/envs/dei_env/lib/python3.9/typing.py", line 220, in _deduplicate
    all_params = set(params)
  File "/home/luminar/mambaforge/envs/dei_env/lib/python3.9/typing.py", line 756, in __hash__
    return hash((self.__origin__, self.__args__))
  File "/home/luminar/mambaforge/envs/dei_env/lib/python3.9/typing.py", line 756, in __hash__
    return hash((self.__origin__, self.__args__))
TypeError: unhashable type: 'list'

**Comment by whardier** [comment] 2022-02-04 18:16
Ditto.

**Comment by bblommers** [comment] 2022-02-04 22:10
Hi @adammacudzinski, @whardier , do you have an MWE (reproducible test case) that throws this error?

**Comment by adammacudzinski** [comment] 2022-02-04 22:36
@bblommers just implement a simple test where you use the decorator `@mock_s3` with Python 3.9. It will fail with the same error that I included above.

**Comment by bblommers** [comment] 2022-02-04 23:22
We have quite a few internal tests that all use the S3-decorator, and they all successfully run against Python3.9.
So my guess is that this error pops up either due to a dependency issue, or something in the test/logic itself causes this error.

**Comment by adammacudzinski** [comment] 2022-02-04 23:26
@bblommers Looks like the error occurs in the `werkzeug` packge. Can you send over the specific version you're using with Python 3.9 ?

**Comment by bblommers** [comment] 2022-02-04 23:29
We're using the latest werkzeug @adammacudzinski , `2.0.2` - that's installed locally on my machine and in our CI.

**Comment by bblommers** [comment] 2022-03-06 23:07
Closing this - if it is an issue in werkzeug, there's not much we can do here. Happy to reopen if there is something amiss in Moto itself though

**Closed by bblommers** 2022-03-06 23:07 UTC
Labels: debugging
