### ISSUE TITLE
Release cycle?

### ISSUE THREAD

**Issue by jessechahal** [spulec/moto#640] opened 2016-06-20 01:33 UTC
So I'm just trying to figure out how often releases are done for moto. We want extend moto whenever we come across gaps in some of the functions in boto but we would rather not maintain our own pypi repo with our custom builds. This is especially important since if we starting versioning moto differently we're going to end up with some conflicts. Is it possible to setup travis to auto deploy to the central pypi repo? https://docs.travis-ci.com/user/deployment/pypi seems to suggest it is quite easy to setup.

**Comment by spulec** [comment] 2016-06-20 01:36
Releases are done about once per month and after any major changes have been merged.

Do you have any examples of other projects doing this?

**Comment by jessechahal** [comment] 2016-06-20 18:25
4 other projects that I know of are:
https://github.com/ivanlei/threatbutt
https://github.com/Pi3rral/expiringpdict
https://github.com/joshmarshall/testnado
https://github.com/tahoe/flask-datatables

**Comment by esc** [comment] 2016-09-29 08:47
Yeah, this is super easy. For the pybuilder project, we basically build a pre-release for PyPi whenever the travis tests on master are green:

 https://pypi.python.org/pypi/pybuilder

You can then install these pre-releases with:

```
pip install --pre pybuilder
```

This is really nice, because a) after you fix a bug, you can simply ask the reporter to install with `--pre` to test and b) some daring people -- like myself -- simply use the `--pre` releases in production, which means that I will notice immediately if it does break even though travis was green.

**Comment by spulec** [comment] 2019-07-01 04:46
I've added a first version of this to the project with https://github.com/spulec/moto/commit/6fa51ac3b423cf8942bb14db2c7de23237cca19d. Feedback welcome.

**Closed by spulec** 2019-07-01 04:46 UTC
Labels: enhancement

**Comment by yan12125** [comment] 2019-07-02 01:26
There is version 1.3.9 on PyPI: https://pypi.org/project/moto/#history, but no 1.3.9 tag in this git repository. Does something go beyond the expectation?

**Comment by spulec** [comment] 2019-07-02 01:53
Yeah, it looks like my script did not work as intended. I didn't intend to release that.

**Comment by yan12125** [comment] 2019-07-02 05:31
Thanks! I'll skip version 1.3.9 for now.

Steve Pulec <notifications@github.com> 於 2019年7月2日 週二 上午9:53寫道：

**Comment by yan12125** [comment] 2019-07-12 10:04
1.3.11 is on PyPI [1] but there is no 1.3.11 tag. Is it another un-intended release?

[1] https://pypi.org/project/moto/

**Comment by spulec** [comment] 2019-07-16 01:01
Ugh, yes. Sorry. I feel good that everything is fixed now.
