### ISSUE TITLE
GetItem throws ValidationException

### ISSUE THREAD

**Issue by michael-yang2** [spulec/moto#2396] opened 2019-08-27 23:21 UTC
I have a table with the schema:

`table = dynamodb.create_table(
                TableName=table_name,
                KeySchema=[
                    {
                        'AttributeName': 'version',
                        'KeyType': 'HASH'  # Partition key
                    },
                    {
                        'AttributeName': 'tid',
                        'KeyType': 'RANGE'  # Sort key
                    }
                ],
                AttributeDefinitions=[
                    {
                        'AttributeName': 'version',
                        'AttributeType': 'S'
                    },
                    {
                        'AttributeName': 'tid',
                        'AttributeType': 'N'
                    },
                ],
                BillingMode='PAY_PER_REQUEST'
            )`
When one tries to get an item from the table, one ends up with the following error: 
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the GetItem operation: Validation Exception
The code:
`response = table.get_item(Key = {
                                            "tid":tid,
                                            "version":version
                                            })`

**Comment by gruebel** [comment] 2019-08-31 16:18
Hi,

could give some details on your problem, which moto version are using and the full example code? It works me fine for me, so what exactly are the variables `tid` and `version`? Is an item already inside the table?

**Comment by michael-yang2** [comment] 2019-09-03 21:15
Hi,
Sorry for the late response. tid and version are both strings, and the table is initally empty.

**Comment by gruebel** [comment] 2019-09-04 20:25
Ok, your main mistake is, that you try to call `get_item()` with `tid` as a string, but you defined it to be `N` a Number. Either you change your `AttributeDefinitions` to
```
table = dynamodb.create_table(
    ...
    AttributeDefinitions = [{
        'AttributeName': 'version',
        'AttributeType': 'S'
    }, {
        'AttributeName': 'tid',
        'AttributeType': 'S'
    }]
)
```
or change `tid` to any numeric value.
Anyway the behavior of moto is also wrong here, it doesn't validate the `AttributeDefinitions` against any follow up request.

**Comment by karthikvadla** [comment] 2020-04-09 19:55
I see the same issue in my pytests. I created a fixture as below.
```
@pytest.fixture(scope="function")
def dynamo_db_table():
    """
        For each test case this fixture will create dummy table
    """
    with mock_dynamodb2():
        client = boto3.client("dynamodb", region_name=os.environ["AWS_REGION"])
        client.create_table(
            AttributeDefinitions=[
                {"AttributeName": "pk", "AttributeType": "S"},
                {"AttributeName": "resource_id", "AttributeType": "S"},
                {"AttributeName": "resource_modified_by", "AttributeType": "S"},
                {"AttributeName": "resource_modified_timestamp", "AttributeType": "N"},
            ],
            TableName=TEST_DYNAMO_TABLE_NAME,
            KeySchema=[{"AttributeName": "pk", "KeyType": "HASH"},
                       {"AttributeName": "resource_modified_timestamp", "KeyType": "RANGE"}],
            ProvisionedThroughput={"ReadCapacityUnits": 5, "WriteCapacityUnits": 5},
            GlobalSecondaryIndexes=[
                {
                    "IndexName": "resourceid_index",
                    "KeySchema": [
                        {"AttributeName": "resource_id", "KeyType": "HASH"},
                        {"AttributeName": "resource_modified_timestamp", "KeyType": "RANGE"},
                    ],
                    "Projection": {"ProjectionType": "ALL"},
                    "ProvisionedThroughput": {"ReadCapacityUnits": 1, "WriteCapacityUnits": 1},
                },
                {
                    "IndexName": "resource_modifiedby_index",
                    "KeySchema": [
                        {"AttributeName": "resource_modified_by", "KeyType": "HASH"},
                        {"AttributeName": "resource_modified_timestamp", "KeyType": "RANGE"},
                    ],
                    "Projection": {"ProjectionType": "ALL"},
                    "ProvisionedThroughput": {"ReadCapacityUnits": 1, "WriteCapacityUnits": 1},
                },
            ],
        )
        table = boto3.resource("dynamodb", region_name=os.environ["AWS_REGION"]).Table(
            TEST_DYNAMO_TABLE_NAME
        )
        # The yield keyword in the fixture will allow
        # this fixture to be kept alive during the whole
        # execution of a test that uses it.
        yield table
        client.delete_table(TableName=TEST_DYNAMO_TABLE_NAME)
```

When i use the above fixture to perform `get_item` operation inside my test case
```
primary_key =  {"pk": "6e2d9b9f819fd9d2fb7bf0423c6b507f"}
get_response = dynamo_db_table.get_item(Key=primary_key)
```
I get error as below
```
        if http.status_code >= 300:
            error_code = parsed_response.get("Error", {}).get("Code")
            error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the GetItem operation: Validation Exception
```
But when i remove RANGE key from schema
```
KeySchema=[{"AttributeName": "pk", "KeyType": "HASH"},
                       {"AttributeName": "resource_modified_timestamp", "KeyType": "RANGE"}]
``` 
changed to 
```
KeySchema=[{"AttributeName": "pk", "KeyType": "HASH"}]
```
Get seems to work. 
But i have created my table in AWS with RANGE key it works fine with get_tiem.

May i know what is causing issue here, i want that RANGE in keyschema for moto db too. Can someone help me with this.

**Comment by alok2k5ingh** [comment] 2020-09-16 12:31
is there any fix for this? I'm getting the same error

**Comment by scottplawrence** [comment] 2020-09-24 07:04
I have the same issue - but only when the key is not in the mock table.  So for example, I have:
```
test_table =dynamodb.create_table(
            TableName='test-table',
            KeySchema=[
                {
                    'AttributeName': 'campaignKey',
                    'KeyType': 'HASH'
                }
            ],
            AttributeDefinitions=[
                {
                    'AttributeName': 'campaignKey',
                    'AttributeType': 'S'
                }
            ],
            ProvisionedThroughput={
                'ReadCapacityUnits': 5,
                'WriteCapacityUnits': 5
            }
        )
item = {
            'campaignKey': 'ACME-TEST'
        }
        test_table.put_item(Item=item)
```

When I run the query:
```
response = test_table.get_item(
                Key={
                    'campaignKey': campaign_key
                }
            )
```

The query works fine with the 'campaign_key' set to 'ACME-TEST', but I get a Validation Exception if it is set to 'ACME-TEST2'.

**Comment by bblommers** [comment] 2020-09-25 12:40
I'm going to close this item, as the original issue was solved (by using the correct AttributeType.

@alok2k5ingh Feel free to open a new issue if you feel anything else is still bugged, ideally with a minimal reproducable test :) 

@scottplawrence Definitely open a new issue for this - I can't reproduce your example, so that might need some more debugging.

**Closed by bblommers** 2020-09-25 12:40 UTC
Labels: debugging

**Comment by scottplawrence** [comment] 2020-09-28 06:12
@bblommers I did some more debugging and the error I was receiving was a query on another table where the table name had a typo - sorry for the confusion!

**Comment by scottplawrence** [comment] 2020-12-13 21:55
Just a note for those who still may encounter this error and stumble upon this post: pay attention to the AWS region when setting up the mock tables in your test file.  

I received the ValidationException when I created my mock table in the eu-west-2 region,  but my default region (from .aws/config on my Mac) was set to the ap-southeast-2 region.  When the code is tested, it cannot find the mock table in the default region, so throws the exception.
