### ISSUE TITLE
boto3 support

### ISSUE THREAD

**Issue by nueverest** [spulec/moto#562] opened 2016-03-10 18:07 UTC
Is there a moto3, that will support boto3?

**Comment by ajk8** [comment] 2016-03-22 17:12
+1

**Comment by hltbra** [comment] 2016-03-22 18:16
Moto implements the AWS APIs and it should be library agnostic. If any service or endpoint doesn't work with boto3, please open an issue. This is a duplicate of https://github.com/spulec/moto/issues/459.

**Closed by hltbra** 2016-03-22 18:16 UTC
