### ISSUE TITLE
mock_dynamodb2 - Inconsistent query result between the mock and dynamodb in terms of missing LastEvaluatedKey

### ISSUE THREAD

**Issue by Nivmorabin** [spulec/moto#3909] opened 2021-05-06 20:47 UTC
Hi,

I experience an inconsistent query result between the mock_dynamodb2 and the actual live dynamodb query result returned from dynamodb in terms of missing LastEvaluatedKey.

I suspect that the limit doesn't apply before the FilterExpression as mentioned in the [documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html)

Please run the following code sample, the query result indeed return 0 items but when I'm running this same query against the actual live dynamodb I receive 0 items with LastEvaluatedKey containing the first item scanned (notice the Limit 1).

Expected result (the first Item I've added in table.put_item in the sample below)
```
{ Items:[], LastEvaluatedKey: {"pk": "TEST", "sk": "ENV#TEST_ENV#FILE#file1", "depth": 4, "file_path": "D/dir1/dir2/dir3/file1", "driveId": "D", "myId": "file1"} }
```
Actual result - the result is correct, but I expect to query with the LastEvaluatedKey a few iterations until I receive LastEvaluatedKey: None due to the Limit 1 (and that's also what returned from dynamodb).
```
{ Items:[], LastEvaluatedKey: None } 
```

moto version 2.0.4

```
import boto3
from moto import mock_dynamodb2
from boto3.dynamodb.conditions import Attr, And, Key
@mock_dynamodb2
def test():
    dynamo_db_resource = boto3.resource("dynamodb", region_name="us-west-2")
    dynamo_db_resource.create_table(TableName="TestTable", KeySchema=[{"AttributeName": "pk", "KeyType": "HASH"},
                                                               {"AttributeName": "sk", "KeyType": "RANGE"}],
                                    AttributeDefinitions=[{"AttributeName": "pk", "AttributeType": "S"},
                                                          {"AttributeName": "sk", "AttributeType": "S"}],
                                    ProvisionedThroughput={"ReadCapacityUnits": 5, "WriteCapacityUnits": 5},
                                    )
    table = dynamo_db_resource.Table("TestTable")

    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#FILE#file1", "depth": 4, "file_path": "D/dir1/dir2/dir3/file1", "driveId": "D", "myId": "file1"})
    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#FILE#file2", "depth": 1, "file_path": "C/file2", "driveId": "C", "myId": "file2"})
    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#FILE#file3", "depth": 2, "file_path": "D/dir1/file3", "driveId": "D", "myId": "file3"})
    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#FILE#file4", "depth": 5, "file_path": "D/dir1/dir4/dir5/dir6/file4", "driveId": "D", "myId": "file4"})
    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#FILE#file5", "depth": 1, "file_path": "C/file5", "driveId": "C", "myId": "file5"})
    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#FILE#file6", "depth": 1, "file_path": "C/file6", "driveId": "C", "myId": "file6"})
    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#DIR#dir4", "depth": 2, "file_path": "D/dir1/dir4", "driveId": "D", "myId": "dir4"})
    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#DIR#dir5", "depth": 3, "file_path": "D/dir1/dir4/dir5", "driveId": "D", "myId": "dir5"})
    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#DIR#dir6", "depth": 4, "file_path": "D/dir1/dir4/dir5/dir6", "driveId": "D", "myId": "dir6"})
    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#DIR#dir2", "depth": 2, "file_path": "D/dir1/dir2", "driveId": "D", "myId": "dir2"})
    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#DIR#dir3", "depth": 3, "file_path": "D/dir1/dir2/dir3", "driveId": "D", "myId": "dir3"})
    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#DIR#dir1", "depth": 1, "file_path": "D/dir1", "driveId": "D", "myId": "dir1"})
    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#DRIVE#D", "depth": 0, "file_path": "D", "driveId": "D", "myId": "D"})
    table.put_item(Item={"pk": "TEST", "sk": "ENV#T_E#DRIVE#C", "depth": 0, "file_path": "C", "driveId": "C", "myId": "C"})

    query_args = {
        "KeyConditionExpression": Key("pk").eq("TEST") & (Key("sk").begins_with("ENV#T_E#FILE")),
        "FilterExpression": And(Attr("depth").eq(1), Attr("file_path").begins_with("D")),
        "Limit": 1
    }

    query_result = table.query(**query_args)
    print(query_result)

if __name__ == "__main__":
    test()
```

Thanks a lot ahead,
Niv

**Comment by bblommers** [comment] 2021-05-07 11:57
Hi @Nivmorabin, looks like you're right - we're only applying the limit at the very end. Marking it as a bug.
Thanks for providing a reproducible test case!

**Comment by Nivmorabin** [comment] 2021-05-07 20:11
Hi @bblommers,
Thanks for the quick response, appreciate it :)

**Comment by ArkadioG** [comment] 2021-12-08 12:40
This bug bites my project too.

When upgrading `moto` from version `2.2.11`  to `2.2.17` our test stopped passing.

We have a table with such properties:
```python
dynamodb_resource.create_table(TableName='transactions,
                               KeySchema=[{'AttributeName':'id', 'KeyType':'HASH'}],
                               AttributeDefinitions=[{'AttributeName':'id', 'AttributeType':'S'},
                                                     {'AttributeName':'expiration_month', 'AttributeType':'S'}],
                               GlobalSecondaryIndexes=[{'IndexName': 'expiration_month',
                                                        'KeySchema': [{'AttributeName': 'expiration_month',
                                                                       'KeyType': 'HASH'}],
                                                        'Projection': {'ProjectionType': 'ALL'}}],
                               ProvisionedThroughput={'ReadCapacityUnits':5, 'WriteCapacityUnits':5})
```

In test, we put one object to the table and launch main logic that query by the index `expiration_month` table with limit == 1 and ProjectionExpression = 'id':
```python
table.query(IndexName='expiration_month',
            KeyConditionExpression=Key('expiration_month').eq(expiration_month),
            ProjectionExpression='id',
            ScanIndexForward=True,
            Limit=1)
```

in result we're getting `KeyError` exception:
```shell
self = <moto.dynamodb2.models.Table object at 0x7f044248acd0>
results = [Item: {'Attributes': {'id': {'S': 'd31d88c2-dea2-45ea-9040-32f53f5e9581:4'}}}]
limit = 1, exclusive_start_key = None, scanned_index = 'expiration_month'

    def _trim_results(self, results, limit, exclusive_start_key, scanned_index=None):
        if exclusive_start_key is not None:
            hash_key = DynamoType(exclusive_start_key.get(self.hash_key_attr))
            range_key = exclusive_start_key.get(self.range_key_attr)
            if range_key is not None:
                range_key = DynamoType(range_key)
            for i in range(len(results)):
                if (
                    results[i].hash_key == hash_key
                    and results[i].range_key == range_key
                ):
                    results = results[i + 1 :]
                    break
    
        last_evaluated_key = None
        size_limit = 1000000  # DynamoDB has a 1MB size limit
        item_size = sum(res.size() for res in results)
        if item_size > size_limit:
            item_size = idx = 0
            while item_size + results[idx].size() < size_limit:
                item_size += results[idx].size()
                idx += 1
            limit = min(limit, idx) if limit else idx
        if limit and len(results) > limit:
            results = results[:limit]
            last_evaluated_key = {self.hash_key_attr: results[-1].hash_key}
            if results[-1].range_key is not None:
                last_evaluated_key[self.range_key_attr] = results[-1].range_key
    
            if scanned_index:
                idx = self.get_index(scanned_index)
                idx_col_list = [i["AttributeName"] for i in idx.schema]
                for col in idx_col_list:
>                   last_evaluated_key[col] = results[-1].attrs[col]
E                   KeyError: 'expiration_month'
```

**Comment by bblommers** [comment] 2021-12-08 15:25
Hi @ArkadioG, can you open a new issue for this? Your example isn't using the 'LastEvaluatedKey', so I don't think it's related.
Would be good to see an MWE as well, as I'm not able to reproduce your issue based on the code you posted here.

**Comment by ArkadioG** [comment] 2021-12-08 17:17
Sure, will prepare new issue.

**Comment by Lilja** [comment] 2022-01-26 13:52
We are also encountering this issue, it seems that the limit is being applied AFTER the filterexpression which is what I would've expect after realizing the same thing.

**Closed** 2022-01-29 11:08 UTC
Labels: bug
