### ISSUE TITLE
httpretty 0.8.7 makes tests hang

### ISSUE THREAD

**Issue by p7k** [spulec/moto#318] opened 2015-02-24 23:49 UTC
• using `py.test`
• upgraded to the latest `moto==0.4.1` which pulled in `httpretty=0.8.7`
==> `@mock_s3` tests started hanging at the end of the module execution.  They do still pass, but the runner never exits.

 downgrading to `httpretty=0.8.6` seems to fix the issue.

**Comment by spulec** [comment] 2015-02-26 04:07
After upgrading httpretty to 0.8.7, I'm still able to run all of the Moto tests (including S3). Could you give a more detailed example of the hanging test?

**Comment by mortaliorchard** [comment] 2015-05-04 13:30
Running into a similar issue – but downgrading httpretty does not resolve the issue. It might be a plugin that is being used by httpretty.

**Comment by spulec** [comment] 2015-08-08 13:50
Going to close this since some progress looks to have been made in HTTPretty and I cannot reproduce the issue. If it stills seems to be happening, feel free to reopen.

**Closed by spulec** 2015-08-08 13:50 UTC
