### ISSUE TITLE
Bug: s3 client download file returns meta data instead of file on every other call

### ISSUE THREAD

**Issue by DanielGeffers** [spulec/moto#4811] opened 2022-01-29 13:41 UTC
Hi,
every second invocation of download_file is returning the file, but every other invocation is returning meta data.

How to reproduce:
```
s3_client = boto3.client('s3', region_name='eu-west-1')
s3_client.create_bucket(Bucket=self.bucket_name, CreateBucketConfiguration={ 'LocationConstraint': 'us-west-1'})
with open('..\\area_type.json', 'rb') as file:
    s3_client.upload_fileobj(file, self.bucket_name, "area_type.json")
s3_client.head_object(Bucket=self.bucket_name, Key="area_type.json")

s3_client.download_file("test_bucket.s3.eu-west-1.amazonaws.com", "area_type.json", "test_file_temp.json")
# this creates a file with content: <?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test_bucket.s3.eu-west-1.amazonaws.com</Name><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>area_type.json</Key><LastModified>2022-01-29T13:23:04.000Z</LastModified><ETag>&#34;b9e351ad74db70cb713126fd490137e4&#34;</ETag><Size>269601</Size><StorageClass>STANDARD</StorageClass><Owner><ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID><DisplayName>webfile</DisplayName></Owner></Contents></ListBucketResult>

s3_client.download_file("test_bucket.s3.eu-west-1.amazonaws.com", "area_type.json", "test_file_temp2.json")
# this returns the actual file

s3_client.download_file("test_bucket.s3.eu-west-1.amazonaws.com", "area_type.json", "test_file_temp3.json")
# this returns the xml meta data again
```

What I was expecting:
3 files with the original content of the file.

What happened:
only the second call got the file.

I think I have the newest versions installed via pip:
moto version 2.3.2
boto version 1.10.38
on
python 2.8.12
using anaconda 4.10.3

The error also seems to occur with get_object and read(), but that is more complicated to show here reliably.

thank you!

**Comment by bblommers** [comment] 2022-01-29 14:19
Hi @DanielGeffers, thanks for raising this, we will look into it.

What version of `responses` do you have installed?

**Comment by DanielGeffers** [comment] 2022-01-30 08:08
Hi @bblommers 
I have version 0.17.0
Thank you very much.

**Comment by bblommers** [comment] 2022-01-30 14:10
Hi @DanielGeffers, I'm not able to reproduce this, I'm afraid - with the test case above, I get the original content three times in a row.

The only change I made to your example is changing this line:
`s3_client.download_file("test_bucket.s3.eu-west-1.amazonaws.com", "area_type.json", "test_file_temp.json")`
to
`s3_client.download_file("test_bucket", "area_type.json", "test_file_temp.json")`
 - as the first parameter should only be the bucket name, not the full URL, but I'm assuming that was a typo.

**Comment by DanielGeffers** [comment] 2022-01-31 08:14
@bblommers 
THANK YOU very much.
I changed the bucket name from a full URL to the name only, and it now works normally. So my issue is solved.

I suspect that there still is a bug in eigther moto or boto3, since having a url as bucket name should not cause an error every second time^^
Should I therefore close the ticket?

**Comment by bblommers** [comment] 2022-01-31 10:55
Happy to hear that, @DanielGeffers!

I agree that it sounds like a bug, but even with the full URL's, I couldn't reproduce it - for me, it would always throw a 404 on the first `download_file`.

See my test file:
https://github.com/bblommers/s3-multiple-downloads/blob/main/test.py

And test execution showing the 404:
https://github.com/bblommers/s3-multiple-downloads/runs/5004616160?check_suite_focus=true

**Comment by bblommers** [comment] 2022-03-04 12:11
Going to close this as unreproducible - do let us know if you find a way to reproduce this though.

**Closed by bblommers** 2022-03-04 12:11 UTC
Labels: debugging
