### ISSUE TITLE
InvalidAccessKeyId - mocking no longer works

### ISSUE THREAD

**Issue by thomashenson** [spulec/moto#2413] opened 2019-09-10 08:08 UTC
**Versions**
- boto==2.49.0
- boto3==1.9.225
- botocore==1.12.225
- moto==1.3.13

This issue has been raised many times before it appears, however after reading through all the reports and changing versions up and down to no avail, I've decided to raise another issue. When I try to mock out AWS using moto, I am getting the following error:

`(InvalidAccessKeyId) when calling the GetObject operation: The AWS Access Key Id you provided does not exist in our records.`

I've tried setting fake credentials using os.environ, I've tried deleting my credentials from the cli configuration, I've tried downgrading botocore/boto3 versions, I've tried re-arranging imports. None of this has helped unfortunately. Hopefully I'm missing something, but if not, there is something wrong.

**The code**
```
@mock_sqs
@mock_s3
@mock_sns
def test_bad_data(self):
    ...
    response = function.lambda_handler(
        None,
        None
    )
    ...
```

Calling the lambda_handler from the test is what lead us to the error:

```
def lambda_handler(event, context):
    ...
    try:
        ...
        s3 = boto3.resource('s3', region_name="eu-west-2")
        sqs = boto3.client('sqs', region_name="eu-west-2")
        lambda_client = boto3.client('lambda', region_name="eu-west-2")
        ...
        input_file = read_from_s3(s3, config['bucket_name'], config['file_name'])
        ...
``` 
It is where the read_from_s3 function is called that it tells me I have invalid credentials, which is the first instance of connecting to AWS. For reference, here is the read_from_s3 function:

```
def read_from_s3(s3, bucket_name, file_name):
    # Read from S3
    object = s3.Object(bucket_name, file_name)
    input_file = object.get()['Body'].read()

    return input_file
```

**What was expected to happen**
Successfully mock AWS in tests.

**What actually happens**
InvalidAccessKeyId error, suggesting that moto mocking isn't working.

If I've missed any important details please let me know so I can update.

**Comment by yabirgb** [comment] 2019-09-19 14:20
Same issue here

**Comment by jkolaric** [comment] 2019-09-20 06:47
I also have the same issue

**Comment by xiang-zhu** [comment] 2019-09-20 21:35
I'm seeing this same issue, had figured out what's happening. It's not caused by library versions, I just updated to use latest version for the libraries

* boto: 2.49.0
* boto3: 1.9.232
* botocore: 1.12.232
* moto: 1.3.13

moto is injecting the botocore_stubber to botocore.handlers.BUILTIN_HANDLERS, but for my case, there's another import from code which includes a line of `s3 = boto3.client('s3')` call outside of functions, so it's causing boto creating the DEFAULT_SESSION without the extra botocore_stubber handler, and it was used when the AWS call in test supposed to be mocked.

The work around is to set boto3.DEFAULT_SESSION to None before the usage of moto mock, and this will cause a creation of new DEFAULT_SESSION with the botocore_stubber handler. 

I did it with a pytest fixture

````python
@pytest.fixture(scope="session")
def clear_default_boto3_session(): 
    boto3.DEFAULT_SESSION = None

def test_with_moto(clear_default_boto3_session):
    with mock_s3():
        s3 = boto3.resource('s3', region_name='us-east-1')
        assert [b for b in s3.buckets.all()] == []
````

**Comment by spulec** [comment] 2019-09-24 02:49
Can you please give a minimal full test case that I can use to reproduce?

It is hard to tell from the above, but it seems like the code you are running inside of the lambda isn't using Moto which is the expected behavior. See more here: https://github.com/spulec/moto/issues/2260

As of now, we haven't implemented a way for the lambda execution to automatically be mocked. The issue above gives some workarounds.

**Comment by spulec** [comment] 2019-09-24 23:18
Yes, that is a known issue. I believe the original issue here may be something else though.

**Comment by paguos** [comment] 2019-12-17 19:50
I have the same problem just using`s3` mock. The workaround didn't solve the issue

**Comment by zenithlight** [comment] 2020-07-24 18:37
> moto is injecting the `botocore_stubber` to `botocore.handlers.BUILTIN_HANDLERS`, but for my case, there's another import from code which includes a line of `s3 = boto3.client('s3')` call outside of functions, That import is before the import moto in my test, so it's causing boto creating the DEFAULT_SESSION without the extra botocore_stubber handler, and it was used when the AWS call in test supposed to be mocked.

@xiang-zhu I have also encountered this same issue. The problem is some of my test files are trying to hit the real S3, and some are trying to hit the moto version. In both test files, `boto3.resource` was created in the top-level so it can be reused across all tests.

As a result, whenever one test file that used the real S3 was run, all proceeding tests that used moto would fail. Creating `boto3.resource` within the test run function (instead of top level of the test file) indeed caused mocking to work, but I do not know how to explain to future test writers that their tests started breaking because they initialized boto3 resources at the top level.

Can you explain why initializing the resource in a function causes mocking to work?

**Comment by cscetbon** [comment] 2020-10-19 03:30
@spulec I have the same issue even without having a global call in my module. I'm trying to run
```
import re
import boto3
from moto import mock_s3
from s3_upload_split import __version__, SplitUploadS3


@mock_s3
def test_handle_content():
    bucket = 'my-bucket'
    conn = boto3.resource('s3', region_name='us-east-1')
    conn.create_bucket(Bucket=bucket)
    prefix = 'd1/d2/d3/d4'
    regex = re.compile(r'(\d{4}-\d{2})-\d{2} \d{2}:\d{2}:\d{2}')

    iterator = [
        dict(dt="2020-02-10 10:04:10", level=10, name="cyril"),
        dict(dt="2020-06-02 16:04:10", level=21, name="cynthia"),
        dict(dt="2019-07-03 12:24:08", level=12, name="steve"),
        dict(dt="2018-01-06 11:14:17", level=17, name="oliver"),
    ]

    SplitUploadS3(bucket, prefix, regex, iterator).handle_content()
```
It uses my module https://github.com/cscetbon/s3-upload-split 
You can see the client is created the class constructor  https://github.com/cscetbon/s3-upload-split/blob/master/s3_upload_split/__init__.py#L34

Any idea what's going on ?

**Comment by jjbuck** [comment] 2020-10-29 17:02
+1 to the above. I'm getting the error "An error occurred (InvalidAccessKeyId) when calling the CreateBucket operation: The AWS Access Key Id you provided
 does not exist in our records." even after setting the environment variables as suggested in https://github.com/spulec/moto#very-important----recommended-usage.

**Comment by lweicker** [comment] 2021-07-22 14:19
hello, I still have the same issue with `moto==2.1.0 boto==2.49.0
boto3==1.17.84 botocore==1.20.112`. I tried the different solution shared in this issue without any success. Any idea how to solve this?

**Comment by whatnick** [comment] 2021-07-27 17:01
+1 Just hit this today.

**Comment by jorenvh1** [comment] 2021-07-28 10:21
Any workaround for this yet? This issue has been out there for quite a while now...

**Comment by bblommers** [comment] 2021-07-28 13:19
@lweicker @whatnick @jorenvh1  Are your imports in the correct order? See the readme for more info: https://github.com/spulec/moto/blob/master/README.md#what-about-those-pesky-imports

As a workaround, if a client is not being mocked, it is always possible to re-assign a mocked client to use in your business logic:
```
class ImportantBusinessLogic:

    def __init__(self):
        self._s3 = boto3.client("s3", region_name="us-east-1")

    def do_important_things(self):
        return self._s3.list_buckets()["Buckets"]


def test_mock_works_when_replacing_client():

    # Import/Initialize the logic outside the mock
    logic = ImportantBusinessLogic()

    m = mock_s3()
    m.start()

    # This will fail, as the S3 client was created before the mock was initialized
    try:
        logic.do_important_things()
    except Exception as e:
        str(e).should.contain("InvalidAccessKeyId")

    # This client is properly mocked
    client_initialized_after_mock = boto3.client("s3", region_name="us-east-1")
    # Reassign, so that our business logic used the mocked client
    logic._s3 = client_initialized_after_mock

    logic.do_important_things().should.equal([])

    m.stop()
```

**Comment by cscetbon** [comment] 2021-10-10 16:32
It seems there's been a PR opened for 3 months, any reason why it's taking so long to get it reviewed, merged in etc... ?

**Comment by bblommers** [comment] 2021-11-09 22:27
The attached PR has now been merged, with a workaround for when the import order can not be reasonably changed.

See the documentation for this feature here: http://docs.getmoto.org/en/latest/docs/getting_started.html#patching-the-client-or-resource

This feature is available as of moto >= 2.2.14.dev13. Please let us know whether that resolves things.

**Comment by cscetbon** [comment] 2021-11-15 19:34
It doesn't work better for me with this new release.

**Comment by bblommers** [comment] 2021-11-15 20:37
Are you explicitly calling the new `patch_client`-method @cscetbon?

A reproducible example would be helpful, to get a better idea of the timeline of when the client is initialized, when the mock is initialized and when the client is mocked.

**Comment by cscetbon** [comment] 2021-11-15 20:39
@bblommers you should have everything you need at https://github.com/spulec/moto/issues/2413#issuecomment-711491276. Also I tried to move this part outside and patch it but got the same result. I shouldn't have it as the call to boto3 is done after boto3 is patched.

**Comment by bblommers** [comment] 2021-11-15 23:01
Ah, apologies @cscetbon, I missed that. 

As a general note, Moto is not guaranteed to behave correctly with multithreading. We don't verify the behaviour, don't have any tests for concurrent processes, etc.

If you do need multithreading, it may be better to use the MotoServer. That way it doesn't matter how many thread/processes there are.
Example on what that would look like can be found in this repo:
https://github.com/bblommers/mock-split-upload-s3/blob/main/package/server_split.py
Successful test run: https://github.com/bblommers/mock-split-upload-s3/runs/4218195853?check_suite_focus=true

**Comment by cscetbon** [comment] 2021-11-16 00:43
> If you do need multithreading, it may be better to use the MotoServer. That way it doesn't matter how many thread/processes there are.
> 
> Example on what that would look like can be found in this repo:
> 
> https://github.com/bblommers/mock-split-upload-s3/blob/main/package/server_split.py
> 
> Successful test run: https://github.com/bblommers/mock-split-upload-s3/runs/4218195853?check_suite_focus=true

Interesting I'm look into it. Thanks !

**Comment by rafaelv-canva** [comment] 2021-12-10 04:07
Is there any news about this issue?

**Comment by bblommers** [comment] 2021-12-10 09:52
@rafaelv-canva There is a workaround for this, to patch the `boto3`-client/resource that is created before the mock starts.

See the documentation for this feature here: http://docs.getmoto.org/en/latest/docs/getting_started.html#patching-the-client-or-resource

Does that solve your usecase?

**Comment by rafaelv-canva** [comment] 2021-12-15 05:56
I'll give it a go and let you know.

**Comment by bblommers** [comment] 2022-02-24 22:46
I'm going to close this, as the relevant solutions have already been posted here.

To recap:
Ensure that the ordering of your imports is correct:

http://docs.getmoto.org/en/latest/docs/getting_started.html#what-about-those-pesky-imports

If the project is so complex that changing the import order is unfeasbiel, it is possible to patch the client afterwards to ensure it is mocked:

http://docs.getmoto.org/en/latest/docs/getting_started.html#patching-the-client-or-resource

**Closed by bblommers** 2022-02-24 22:46 UTC
Labels: debugging

**Comment by ciurlaro42** [comment] 2022-11-24 15:20
@bblommers, in case you might be interested the problem seems to persist:

# module 1
```python
def get_s3_client(aws_session, aws_region_name, debug):
    """ :return: Returns an S3 boto3 Client object """
    config = Config(retries={'max_attempts': 3, 'mode': "adaptive"})
    client = aws_session.client("s3", region_name=aws_region_name, config=config)

    if debug:
        patch_client(client)

    return client
```

# module 2
```python
s3_client_mock = get_s3_client(
    boto3.Session(),
    aws_region_name=AWS_REGION_NAME,
    debug=True
)

# This method fails because it is using the AWS credentials
result = s3_client_mock.list_buckets()
```

# requirements
```
boto3==1.23.6
moto[s3]==4.0.10
```
