### ISSUE TITLE
Unable to Mock Profiles

### ISSUE THREAD

**Issue by HenryHoggard** [spulec/moto#2634] opened 2019-12-12 12:27 UTC
This is a duplicate of the following issue seems to have been closed without a fix: https://github.com/spulec/moto/issues/889

My tests are failing because it requires the profiles to actually exist within `~/.aws/config`. Given that this is a mocking library, we should be able to mock this functionality. Otherwise I am going to have to overwrite `/.aws/config` files anywhere that the tests are run for this to work.

Example error:

```
 botocore.exceptions.ProfileNotFound: The config profile (myenv) could not be found
```

Example code

```
@mock_ssm
def test_whatever():
    env = boto3.session.Session(profile_name="myenv")
    ssm = env.client('ssm')
    ...
```

This can be fixed on my machine by adding the valid profiles, but I need these tests to be portable so that is not an option, ideally this should be mockable.

**Comment by mikegrima** [comment] 2019-12-15 01:03
Can you verify if this is still a problem with the latest `master`? (do a pip install from git via `pip install git+git://github.com/spulec/moto@master#egg=moto`)

**Comment by westonplatter** [comment] 2020-01-02 21:13
@mikegrima  Running into the same issue. I installed `1.3.15.dev0` and got the following error,

```
self = <botocore.session.Session object at 0x7f51f11e2950>

    def get_scoped_config(self):
        """
        Returns the config values from the config file scoped to the current
        profile.

        The configuration data is loaded **only** from the config file.
        It does not resolve variables based on different locations
        (e.g. first from the session instance, then from environment
        variables, then from the config file).  If you want this lookup
        behavior, use the ``get_config_variable`` method instead.

        Note that this configuration is specific to a single profile (the
        ``profile`` session variable).

        If the ``profile`` session variable is set and the profile does
        not exist in the config file, a ``ProfileNotFound`` exception
        will be raised.

        :raises: ConfigNotFound, ConfigParseError, ProfileNotFound
        :rtype: dict

        """
        profile_name = self.get_config_variable('profile')
        profile_map = self._build_profile_map()
        # If a profile is not explicitly set return the default
        # profile config or an empty config dict if we don't have
        # a default profile.
        if profile_name is None:
            return profile_map.get('default', {})
        elif profile_name not in profile_map:
            # Otherwise if they specified a profile, it has to
            # exist (even if it's the default profile) otherwise
            # we complain.
>           raise ProfileNotFound(profile=profile_name)
E           botocore.exceptions.ProfileNotFound: The config profile (default) could not be found
```

**Comment by rawrgulmuffins** [comment] 2020-07-02 21:29
I seem to also be hitting this on 

```
boto3==1.14.14
botocore==1.17.14
moto==1.3.14
```

And 
```
boto3==1.10.20
botocore==1.13.40
moto==1.3.8
```

```
ImportError while loading conftest '/home/python/app/lambda/tests/conftest.py'.

tests/__init__.py:6: in <module>
    from moto import mock_kinesis
/usr/local/lib/python3.8/site-packages/moto/__init__.py:4: in <module>
    from .apigateway import mock_apigateway, mock_apigateway_deprecated  # noqa
/usr/local/lib/python3.8/site-packages/moto/apigateway/__init__.py:2: in <module>
    from .models import apigateway_backends
/usr/local/lib/python3.8/site-packages/moto/apigateway/models.py:843: in <module>
    for region_name in Session().get_available_regions("apigateway"):
/usr/local/lib/python3.8/site-packages/boto3/session.py:80: in __init__
    self._setup_loader()
/usr/local/lib/python3.8/site-packages/boto3/session.py:120: in _setup_loader
    self._loader = self._session.get_component('data_loader')
/usr/local/lib/python3.8/site-packages/botocore/session.py:682: in get_component
    return self._components.get_component(name)
/usr/local/lib/python3.8/site-packages/botocore/session.py:919: in get_component
    self._components[name] = factory()
/usr/local/lib/python3.8/site-packages/botocore/session.py:155: in <lambda>
    lambda:  create_loader(self.get_config_variable('data_path')))
/usr/local/lib/python3.8/site-packages/botocore/session.py:237: in get_config_variable
    return self.get_component('config_store').get_config_variable(
/usr/local/lib/python3.8/site-packages/botocore/configprovider.py:293: in get_config_variable
    return provider.provide()
/usr/local/lib/python3.8/site-packages/botocore/configprovider.py:390: in provide
    value = provider.provide()
/usr/local/lib/python3.8/site-packages/botocore/configprovider.py:451: in provide
    scoped_config = self._session.get_scoped_config()
/usr/local/lib/python3.8/site-packages/botocore/session.py:337: in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
E   botocore.exceptions.ProfileNotFound: The config profile (default) could not be found
```

**Comment by mikegrima** [comment] 2020-07-02 21:39
You'll need to provide the code in the tests that's running. Also, please verify that this is not an issue by uninstalling moto: `pip uninstall moto`, and re-installing it this way: `pip install git+git://github.com/spulec/moto@master#egg=moto`.

**Comment by rawrgulmuffins** [comment] 2020-07-02 21:42
@mikegrima I'm running in a docker container and I'm currently setting things to rebuild on each test run. The particular test setup function that's failing is:

```
"""Helper functions for testing the platform gateway.
"""
from typing import Dict, Union
import os

from moto import mock_kinesis This line is failing

def get_inserted_records(kinesis) -> Union[Dict, None]:
    """Helper function that will grab all of the inserted recrods for a test
    kinesis stream (or a real one if boto was not mocked directly or through
    moto)
    """
    stream_name = os.environ['STREAM']
    stream_response = kinesis.describe_stream(StreamName=stream_name)
    shard_id = stream_response['StreamDescription']['Shards'][0]['ShardId']
    shard_itr_response = kinesis.get_shard_iterator(
        StreamName=stream_name,
        ShardId=shard_id,
        ShardIteratorType='TRIM_HORIZON')
    shard_iterator = shard_itr_response['ShardIterator']
    return kinesis.get_records(ShardIterator=shard_iterator)

@mock_kinesis
def setup_kinesis_stream():
    """Generic helper fixture that adds a mocked kinesis stream for a unit test
    to use to see if records are written as outputs.
    """
    # Need to do this import after the test environment variables are setup
    # which means in this function
    import boto3 # pylint: disable=import-outside-toplevel
    stream_name = os.environ['STREAM']
    conn = boto3.client('kinesis', os.environ['REGION'])
    conn.create_stream(StreamName=stream_name, ShardCount=1)
    return conn
```
Important to note that this is failing locally if I `mv ~/.aws/config ~/.aws/config_backup` or remotely in our Jenkins environment which doesn't have a profile.

**Comment by mikegrima** [comment] 2020-07-02 21:48
Is it failing on the `from moto import mock_kinesis` line? Also, what code is calling `setup_kinesis_stream()`?

**Comment by rawrgulmuffins** [comment] 2020-07-02 21:57
I actually have this reproducing locally now. If I `mv ~/.aws ~/.aws_backup` I get the above error.

> Is it failing on the from moto import mock_kinesis line? 

It's failing on the import. This is in my `tests/__init__.py` file so it's not even getting to the tests themselves.

It looks like my docker setup library is setting an `AWS_PROFILE` environment variable so if I modify `__init__.py` file to 

```
saved_profile = os.environ['AWS_PROFILE']
del os.environ['AWS_PROFILE'] # our docker startup library is setting this file.
from moto import mock_kinesis
```  

We actually get our tests to run again and the import succeeds but if I do

``` 
alordthorsen@ew-mbp-alexlt01 ~/git/platform/platform-gateway/lambda :)% mv ~/.aws/credentials ~/.aws/credentials_backup
```
we hit `raise NoCredentialsError\\nbotocore.exceptions.NoCredentialsError: Unable to locate credentials\\n"}'}` in our response code. 

> Also, what code is calling setup_kinesis_stream()?

Here's the test that would run the setup function

```
@mock_secretsmanager
@mock_apigateway
@mock_kinesis
def test_ingesting_array_data(test_handler) -> None:
    """Regression test for https://esentire.atlassian.net/browse/PLATLAS-858"""

    auth_body = get_jwt(test_handler)
    body = copy.deepcopy(VALID_INGESTION_BODY)
    # Test data
    body["body"] = BLUESTEEL_EXAMPLE_ARRAY

    # Auth data setup for all tests
    body['params']['header']['authorization'] = f'bearer {auth_body["jwt"]}'
    body['params']['header']['X-Api-Key'] = auth_body['x-api-key-value']

    # NOTE: Wasn't able to get this to correctly work as a pytest fixture. Kept
    # hitting security token errors. Should open a moto ticket about this.
    # NOTE: There is a bug where `get_jwt.setup_auth_token` resets
    # test_handler.KINESIS to None and therefor the call to create the kinesis
    # stream needs to be after that call.
    kinesis_stream = setup_kinesis_stream()
    test_handler.KINESIS = kinesis_stream

    response = test_handler.handler(body, None)
    assert response["statusCode"] == 200
    pushed_signals = get_inserted_records(kinesis_stream)
    actual = pushed_signals["Records"]
    assert len(actual) == 2
    assert json.loads(actual[0]["Data"]) == BLUESTEEL_EXAMPLE_ARRAY[0]
    assert json.loads(actual[1]["Data"]) == BLUESTEEL_EXAMPLE_ARRAY[1]
```

**Comment by rawrgulmuffins** [comment] 2020-07-02 22:05
The specific boto3/moto call is 

```
    response = CLIENT_API.get_api_keys(includeValues=True)
```

Which is equivilent to

```
    response = boto3.client('apigateway', region_name=REGION).get_api_keys(includeValues=True)
```

With the full response being

```
RESPONSE {'isBase64Encoded': 'false', 'statusCode': 400, 'headers': {'Content-Type': 'application/json'}, 'body': '{"msg": "handler exception Unable to locate credentials 156 Traceback (most recent call last):\\n  File \\"/home/python/app/lambda/platform_gateway_lambda/ha
ndler.py\\", line 151, in handler\\n    return fct(event, context)\\n  File \\"/home/python/app/lambda/platform_gateway_lambda/handler.py\\", line 242, in auth\\n    xapikey = auth_create_xapikey(xak, key_name)\\n  File \\"/home/python/app/lambda/platform_gateway_lambda/h
andler.py\\", line 330, in auth_create_xapikey\\n    response = get_api_key_by_value(xak)\\n  File \\"/home/python/app/lambda/platform_gateway_lambda/handler.py\\", line 576, in get_api_key_by_value\\n    response = CLIENT_API.get_api_keys(includeValues=True)\\n  File \\"
/usr/local/lib/python3.8/site-packages/botocore/client.py\\", line 316, in _api_call\\n    return self._make_api_call(operation_name, kwargs)\\n  File \\"/usr/local/lib/python3.8/site-packages/botocore/client.py\\", line 621, in _make_api_call\\n    http, parsed_response
= self._make_request(\\n  File \\"/usr/local/lib/python3.8/site-packages/botocore/client.py\\", line 641, in _make_request\\n    return self._endpoint.make_request(operation_model, request_dict)\\n  File \\"/usr/local/lib/python3.8/site-packages/botocore/endpoint.py\\", l
ine 102, in make_request\\n    return self._send_request(request_dict, operation_model)\\n  File \\"/usr/local/lib/python3.8/site-packages/botocore/endpoint.py\\", line 132, in _send_request\\n    request = self.create_request(request_dict, operation_model)\\n  File \\"/u
sr/local/lib/python3.8/site-packages/botocore/endpoint.py\\", line 115, in create_request\\n    self._event_emitter.emit(event_name, request=request,\\n  File \\"/usr/local/lib/python3.8/site-packages/botocore/hooks.py\\", line 356, in emit\\n    return self._emitter.emit
(aliased_event_name, **kwargs)\\n  File \\"/usr/local/lib/python3.8/site-packages/botocore/hooks.py\\", line 228, in emit\\n    return self._emit(event_name, kwargs)\\n  File \\"/usr/local/lib/python3.8/site-packages/botocore/hooks.py\\", line 211, in _emit\\n    response
 = handler(**kwargs)\\n  File \\"/usr/local/lib/python3.8/site-packages/botocore/signers.py\\", line 90, in handler\\n    return self.sign(operation_name, request)\\n  File \\"/usr/local/lib/python3.8/site-packages/botocore/signers.py\\", line 160, in sign\\n    auth.add_
auth(request)\\n  File \\"/usr/local/lib/python3.8/site-packages/botocore/auth.py\\", line 357, in add_auth\\n    raise NoCredentialsError\\nbotocore.exceptions.NoCredentialsError: Unable to locate credentials\\n"}'}
```

**Comment by rawrgulmuffins** [comment] 2020-07-02 22:10
Followed the suggestion of doing 

```
os.environ["AWS_ACCESS_KEY_ID"] = "test"
os.environ["AWS_SECRET_ACCESS_KEY"] = "test"
```

In https://github.com/spulec/moto/issues/1941 and this got my unit tests to pass. 0.o

**Comment by rawrgulmuffins** [comment] 2020-07-02 22:16
This seems like a PBCK issue. =P

**Comment by rawrgulmuffins** [comment] 2020-07-02 22:55
Ah, I finally figured out why this succeeded in the past but fails now.

If you have no credentials file, no profile, and `AWS_SECRET_ACCESS_KEY`, `AWS_ACCESS_KEY_ID`, `AWS_SECURITY_TOKEN` and `AWS_SESSION_TOKEN` aren't set then no credentials are searched for.

**Comment by mikegrima** [comment] 2020-07-02 23:02
We do have this documented https://github.com/spulec/moto#other-caveats. Would also recommend checking out: https://github.com/spulec/moto#very-important----recommended-usage

**Comment by areeb-lululemon** [comment] 2020-11-26 06:56
> This is a duplicate of the following issue seems to have been closed without a fix: #889
> 
> My tests are failing because it requires the profiles to actually exist within `~/.aws/config`. Given that this is a mocking library, we should be able to mock this functionality. Otherwise I am going to have to overwrite `/.aws/config` files anywhere that the tests are run for this to work.
> 
> Example error:
> 
> ```
>  botocore.exceptions.ProfileNotFound: The config profile (myenv) could not be found
> ```
> 
> Example code
> 
> ```
> @mock_ssm
> def test_whatever():
>     env = boto3.session.Session(profile_name="myenv")
>     ssm = env.client('ssm')
>     ...
> ```
> 
> This can be fixed on my machine by adding the valid profiles, but I need these tests to be portable so that is not an option, ideally this should be mockable.

You can use the `AWS_SHARED_CREDENTIALS_FILE` environment variable, to point it to a dummy creds file which can be kept in the `tests` folder.
You can define your profiles there.

**Comment by red8888** [comment] 2020-12-29 23:33
Moto should ignore the variable completely shouldnt it? I make heavy use of AWS_PROFILE. I should not have to unset that before running my unit tests

**Comment by mikegrima** [comment] 2020-12-30 01:31
I'm _pretty sure_ that this has been fixed where you shouldn't need to do this anymore, however it's also good to add as a safety precaution in the event that the mocking fails. There are a variety of reasons for why the mock can fail, which I outlined here: https://github.com/spulec/moto#very-important----recommended-usage

**Comment by LeoQuote** [comment] 2021-05-17 07:52
So wierd that for my test case moto-1.3.13 works for me while moto-2.0.7 doesnt

**Comment by gedd-shelf** [comment] 2021-07-08 11:29
Here is a workaround I found for anyone who is still having issues with this: https://stackoverflow.com/questions/59535311/moto-does-not-appear-to-be-mocking-aws-interactions-in-a-pytest/65017491#65017491

Basically you need to create a AWS_SHARED_CREDENTIALS_FILE env var that points to a fake aws creds file in your test suite

**Comment by bblommers** [comment] 2022-03-24 22:20
I'll close this, with multiple fixes/workarounds already linked here.

As a reminder, considering the docs have been reworked since, here is a link to the `Recommended Usage` docs that are mentioned earlier in this topic:
http://docs.getmoto.org/en/latest/docs/getting_started.html#recommended-usage

**Closed by bblommers** 2022-03-24 22:20 UTC
Labels: bug

**Comment by mherrmann** [comment] 2022-11-09 14:30
As a note for other readers: I got error

    botocore.exceptions.ProfileNotFound: The config profile () could not be found

when I had an empty `AWS_PROFILE` environment variable set with moto 2.3.2, boto 2.49.0, boto3 1.26.5, botocore 1.29.5. (I know these are old versions.)

**Comment by sairamkrish** [comment] 2025-05-26 12:52
Here is a workaround for anyone who is still having issues with this:
https://stackoverflow.com/a/79638942/1294667
