### ISSUE TITLE
cloudwatch-fluent-metrics and moto don't play nicely

### ISSUE THREAD

**Issue by romcab** [spulec/moto#2581] opened 2019-11-20 02:37 UTC
**Problem:**  
 I am receiving the error below when mocking the cloudwatch. Based from the stack trace, it happens when executing the code below.

- moto/cloudwatch/responses.py:81: in put_metric_data
- self.cloudwatch_backend.put_metric_data(namespace, metric_data)
- moto/cloudwatch/models.py:235: in put_metric_data

**Error:**

- ValueError: time data '2019-11-20T02:26:58Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'. 

**Setup:**

- python 3.7.5
- boto=2.49.0
- boto3=1.10.20
- botocore=1.13.20
- moto=1.3.14
- cloudwatch-fluent-metrics=0.5.3

**Step to reproduced:**
@mock_cloudwatch
def test_put_metric_data():
    metrics = BufferedFluentMetric().with_namespace('my-namespace')
    metrics.with_timer('RequestLatency')
    metrics.elapsed(MetricName='RequestLatency', TimerName='RequestLatency')
    metrics.flush()

**Comment by bblommers** [comment] 2020-01-15 15:49
Duplicate of #2614 

I'll close this one, as the other one is more recent/more likely to be seen

**Closed by bblommers** 2020-01-15 15:49 UTC
