### ISSUE TITLE
_call_s3("upload_part") doesn't set `ETag` in response

### ISSUE THREAD

**Issue by shearer12345** [spulec/moto#4665] opened 2021-12-06 11:03 UTC
When writing a multi-part file to S3 using s3fs, s3fs expects `ETag` to be set in the response dictionary, and when using mock_s3it is missing. The same code without mock_s3 doesn't raise, writes to s3, and retun `ETag` in the response dictionary 
```
{'ResponseMetadata': ...,
'ETag': '"79b281060d337b9b2b84ccf390adcf74"'}
```

### Reproduction

```
import boto3
import botocore
import moto
from s3fs import S3FileSystem

with moto.mock_s3():
    class MockedAWSResponse(botocore.awsrequest.AWSResponse):
        raw_headers = {}  # type: ignore
        async def read(self):  # type: ignore
            return self.text

    botocore.awsrequest.AWSResponse = MockedAWSResponse
    try:
        moto.core.models.AWSResponse = MockedAWSResponse
    except AttributeError as err:
        if str(err) == "module 'moto' has no attribute 'core'":
            raise AttributeError(
               "moto mock needs to be present prior to setting up the mockedAWSResponse") from err
        raise err

    s3_resource = boto3.resource("s3")
    test_bucket = s3_resource.Bucket("test-mocked-s3-bucket")
    test_bucket.create()

    s3 = S3FileSystem()

    with s3.open(f'{test_bucket.name}/small_file.txt', mode='wb') as small_file:
        small_file.write(2 ** 2 * b'a')

    with s3.open(f'{test_bucket.name}/just_small_enough_file.txt', mode='wb') as just_small_enough_file:
        just_small_enough_file.write((just_small_enough_file.blocksize-1) * b'a')

    # raises KeyError: 'ETag' at s3fs/core.py#1958 in _upload_chunk
    #     self.parts.append({"PartNumber": part, "ETag": out["ETag"]})
    with s3.open(f'{test_bucket.name}/just_too_big_file.txt', mode='wb') as just_too_big_file:
        just_too_big_file.write(just_too_big_file.blocksize * b'a')

```

### Versions

Running on Windows

boto3=1.19.8
botocore=1.22.8
moto=2.2.17
s3fs==2021.11.1

install through pip (requirements.txt), or through poetry - both show the same behaviour

using Python mocks, using AWSResponse modifications as in https://github.com/aio-libs/aiobotocore/issues/755 to allow s3fs to work.

This **may** be related to #4472 and #4548 ("Multipart upload tags not applied")

```
Traceback (most recent call last):
  File "xxxxxxxxxxxx/code/test/key_error__etag/key_error__etag_test.py", line 34, in <module>
    just_too_big_file.write(just_too_big_file.blocksize * b'a')
  File "xxxxxxxxxxxx\code\test\key_error__etag\env\lib\site-packages\fsspec\spec.py", line 1481, in write
    self.flush()
  File "xxxxxxxxxxxx\code\test\key_error__etag\env\lib\site-packages\fsspec\spec.py", line 1522, in flush
    if self._upload_chunk(final=force) is not False:
  File "xxxxxxxxxxxx\code\test\key_error__etag\env\lib\site-packages\s3fs\core.py", line 1958, in _upload_chunk
    self.parts.append({"PartNumber": part, "ETag": out["ETag"]})
KeyError: 'ETag'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xxxxxxxxxxxx/code/test/key_error__etag/key_error__etag_test.py", line 34, in <module>
    just_too_big_file.write(just_too_big_file.blocksize * b'a')
  File "xxxxxxxxxxxx\code\test\key_error__etag\env\lib\site-packages\fsspec\spec.py", line 1684, in __exit__
    self.close()
  File "xxxxxxxxxxxx\code\test\key_error__etag\env\lib\site-packages\fsspec\spec.py", line 1651, in close
    self.flush(force=True)
  File "xxxxxxxxxxxx\code\test\key_error__etag\env\lib\site-packages\fsspec\spec.py", line 1522, in flush
    if self._upload_chunk(final=force) is not False:
  File "xxxxxxxxxxxx\code\test\key_error__etag\env\lib\site-packages\s3fs\core.py", line 1958, in _upload_chunk
    self.parts.append({"PartNumber": part, "ETag": out["ETag"]})
KeyError: 'ETag'
python-BaseException

Process finished with exit code 1
```

**Comment by shearer12345** [comment] 2021-12-06 11:07
I could submit a PR for testing this, but wouldn't know where to do the actual fix. Let me know if the test PR would be helpful

**Comment by bblommers** [comment] 2021-12-06 13:03
A PR would be helpful, @shearer12345! There are a few tests (in `tests/test_s3/test_multipart.py`, I believe) that verify the ETag response already, so I'm not quite sure what's still missing from Moto without seeing an example.

**Comment by bblommers** [comment] 2022-02-19 00:07
Without something reproducible, there's not much we can do here, so I'm going to close this. Happy to reopen the moment there is a PR/test case to showcase this issue

**Closed by bblommers** 2022-02-19 00:07 UTC
Labels: bug

**Comment by jrobbins-LiveData** [comment] 2022-03-05 22:45
@bblommers , this test seems to reproduce the `KeyError('ETag')` exception.

Versions
Running on Windows 10 Version	10.0.19044

aiobotocore=2.1.1
boto3=1.20.24
botocore=1.23.24
moto=3.0.5
s3fs==2022.2.0

```python
import os

import boto3
import botocore
import moto
import pytest
import s3fs
from moto import mock_s3


def test_etag():
    bucket_name = 'test_bucket'
    os.environ['AWS_DEFAULT_REGION'] = 'us-east-1'

    with mock_s3():
        class MockedAWSResponse(botocore.awsrequest.AWSResponse):
            raw_headers = {}

            async def read(self):
                return self.text.encode()

        botocore.awsrequest.AWSResponse = MockedAWSResponse
        moto.core.models.AWSResponse = MockedAWSResponse

        boto3.resource('s3').create_bucket(Bucket=bucket_name)

        s3 = s3fs.S3FileSystem(anon=False, s3_additional_kwargs={'ServerSideEncryption': 'AES256'})

        with s3.open(f'{bucket_name}/test_file.bin', 'wb') as f:
            f.write(b'somebytes')

        with pytest.raises(KeyError) as e_info:
            with s3.open(f'{bucket_name}/test_file.bin', 'rb') as f:
                print(f.read())

        assert e_info.value.args[0] == 'ETag'
```

**Comment by bblommers** [comment] 2022-03-06 12:17
S3FS expects the ETag to exist in the headers, but the `raw_headers` are set to an empty dict in this example.

This would work better:
```
class MockedAWSResponse(botocore.awsrequest.AWSResponse):
    #raw_headers = {}

    @property
    def raw_headers(self):
        # Turn the existing headers into a list of (byte, byte) tuples
        return [(str(k).encode("utf-8"), str(v).encode("utf-8")) for (k,v) in self.headers._dict.items()]
```

With this fix it fails further down the line, when reading the content - looks to me like the `read`-method also needs to change. But I don't know enough about S3FS or aiobotocore to understand how (or why this `MockedAWSResponse` is even necessary).

**Comment by jrobbins-LiveData** [comment] 2022-03-06 16:09
I see.  Thanks for explaining, especially this seems to be an `aiobotocore` issue.  If you don't mind a bit more discussion, I'd like to file an issue with either `s3fs` or `aiobotocore`, but am new to all this code, unfortunately.

`aiobotocore` has a file `endpoint.py` which has this code

```python
    response_dict = {
        # botocore converts keys to str, so make sure that they are in
        # the expected case. See detailed discussion here:
        # https://github.com/aio-libs/aiobotocore/pull/116
        # aiohttp's CIMultiDict camel cases the headers :(
        'headers': HTTPHeaderDict(
            {k.decode('utf-8').lower(): v.decode('utf-8')
             for k, v in http_response.raw_headers}),
        'status_code': http_response.status_code,
        'context': {
            'operation_name': operation_model.name,
        }
    }
```

which assumes that the relevant `http_response` has a `raw_headers` attribute.  But in this test code I wrote


```python
import os

import boto3
import s3fs
from moto import mock_s3


def test_mock_write():
    bucket_name = 'jsr-test-bucket'
    os.environ['AWS_DEFAULT_REGION'] = 'us-east-1'

    with mock_s3():
        boto3.resource('s3').create_bucket(Bucket=bucket_name)
        s3 = s3fs.S3FileSystem(anon=False, s3_additional_kwargs={'ServerSideEncryption': 'AES256'})

        with s3.open(f'{bucket_name}/test_file.bin', 'wb') as f:
            f.write(b'somebytes')
```

when I break on `f.write(...)`, `http_response` looks like this

<img width="689" alt="image" src="https://user-images.githubusercontent.com/79278744/156930673-a8883bb0-b2b0-4ac6-8aab-d8581ac3b6ef.png">


So, apparently, the immediate cause of the problem I am having with mocking s3 using `moto` with `s3fs`  is that `s3fs` relies on `aiobotocore` which assumes that such `http_response`s have a `raw_headers` attribute.  Since I don't know what the difference is between `headers` and `raw_headers`, I don't know what's going on here.

However, since this code (without the `mock_s3()`) works with AWS, I wonder if `aiobotocore` is using some aspect of `boto3` or `botocore` which `moto` isn't mocking 100%?

Sorry for the ton of words, but I guess I'm wondering if `moto` ought to be adding a `raw_headers` to the `http_response` it apparently is generating?

**Comment by bblommers** [comment] 2022-03-06 22:35
That `raw_headers`-attribute is only defined by `aiobotocore`, not by `botocore`. So the underlying issue is that `aiobotocore` is using a custom `AWSResponse`-class that does not follow the same signature as botocore.

They are aware of it, see this issue: https://github.com/aio-libs/aiobotocore/issues/755

**Comment by jrobbins-LiveData** [comment] 2022-03-07 00:34
Thank you very much for explaining this!
