### ISSUE TITLE
S3 - Allow create_bucket(region=None), instead of throwing IllegalLocationConstraintException

### ISSUE THREAD

**Issue by changliuit** [spulec/moto#3292] opened 2020-09-08 01:07 UTC
Version: moto: 1.3.15; botocore: 1.17.56
python 3.7.4

was working before with moto 1.3.14, but stopped working in 1.3.15

error:

```        if http.status_code >= 300:
            error_code = parsed_response.get("Error", {}).get("Code")
            error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

../../../.venv/lib/python3.7/site-packages/botocore/client.py:656: ClientError
```

test as below:

```    
    @pytest.fixture(scope='class')
    def s3_client(self):
        s3_client = boto3.client('s3', region_name='ap-southeast-2')
        yield s3_client

    @mock_s3
    def test_store_new_supplier_file(self, config, s3_client):
        s3_client.create_bucket(Bucket='test')
```

**Comment by bblommers** [comment] 2020-09-08 07:49
Hi @changliuit, this mimics the behaviour from AWS itself.
If the region is anything else then the default (us-east-1), the Location has to be specified using the CreateBucketConfigurationOption. See this example: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-example-creating-buckets.html

**Comment by changliuit** [comment] 2020-09-08 10:15
Hey @bblommers  thanks for your reply! Right now the `create_bucket` is not exactly the same behaviour as the boto one which allows `region=None` in create_bucket function. Can we have something here similar to the boto code -- if region is None, get it from the client?

Regards
Chang

**Comment by bblommers** [comment] 2020-09-08 10:28
Hi @changliuit, I wasn't aware of the region=None behaviour! Will mark it as an enhancement

**Comment by changliuit** [comment] 2020-09-08 23:46
thanks @bblommers that'll be great

**Comment by jmehnle** [comment] 2020-09-17 03:17
I understand I can work around this by specifying a region, but I choose not to (I have too many `create_bucket` calls in my unit tests, and running on `moto` 1.3.14 for a while longer is the lesser evil), and so this is effectively preventing me from upgrading to `moto` 1.3.16. :(

**Comment by bblommers** [comment] 2020-09-30 11:38
Hi @changliuit, can you share an example test of the region=none?
I assumed you meant `s3.create_bucket(Bucket=bucket_name, CreateBucketConfiguration={"LocationConstraint": None},)`, but that doesn't work anyway.

**Comment by christian-ertl** [comment] 2020-10-20 18:01
Moto 1.3.16 also fails for s3.create_bucket(Bucket=bucket_name).

**Comment by wmarcuse** [comment] 2020-10-28 18:13
I got this error with mocking S3, seems to be the trick that the mocked S3 client only accepts region `us-east-1`. As it is a mocked bucket it doesn't matter..

```
    conn = boto3.resource("s3", region_name="us-east-1")
    conn.create_bucket(Bucket=os.environ["S3_BUCKET_NAME"]
```

**Comment by kaito-albert** [comment] 2020-11-12 08:53
I got this error with even set `region=ap-northeast-1`.
Don't forget tokyo!

**Comment by PuneethaPai** [comment] 2021-02-01 08:44
I was getting the same error, because mock s3 expects default region to be `us-east-1`.
We can use env variable to do so, instead of making code changes in all test cases:
```
export AWS_DEFAULT_REGION=us-east-1
```

**Comment by andreif** [comment] 2022-01-07 14:42
Ended up with
```py
os.environ["AWS_DEFAULT_REGION"] = moto.s3.responses.DEFAULT_REGION_NAME = "eu-west-1"
```

**Comment by bblommers** [comment] 2022-02-24 22:41
Closing this, as the original report was not a bug, as far as I'm concerned.

**Closed by bblommers** 2022-02-24 22:41 UTC
Labels: enhancement

**Comment by forzagreen** [comment] 2022-04-15 09:52
Works with `moto==3.1.4`:
```python
s3_client.create_bucket(
    Bucket="test",
    CreateBucketConfiguration={"LocationConstraint": "eu-west-1"}
)
```

**Comment by d33tah** [comment] 2024-09-27 09:57
Is eu-west-1 somehow special here? I'm still getting this error after trying the advice here - with the exception of not being able to set moto.s3.responses.DEFAULT_REGION_NAME because I'm using it through docker.
