### ISSUE TITLE
Mocking s3 client upload test speed

### ISSUE THREAD

**Issue by pmart123** [spulec/moto#656] opened 2016-07-03 13:17 UTC
I have a small adapter class for s3. I switched to using moto for mocking. I noticed that a test involving mocking a file/data upload took a significant amount of time to run as a test(1.5-3 seconds). I reproduced the code below. Is there a reason/better way to mock the behavior with moto? I am running boto3 on Python 3.5.1.

```python

import unittest
from tempfile import NamedTemporaryFile

import boto3
import botocore
import moto

class S3Bucket:

    def __init__(self, bucket_name):
        self.bucket_name = bucket_name
        self.client = boto3.client('s3')

    def upload(self,  bucket_key, source_uri, **kwargs):
        self.client.upload_file(Filename=source_uri,
                                Bucket=self.bucket_name,
                                Key=bucket_key,
                                ExtraArgs=kwargs)


BUCKET_NAME = 'finegar-test-bucket'
BUCKET_KEY = 'fake_key'


@moto.mock_s3
class TestS3Bucket(unittest.TestCase):

    def setUp(self):
        self.s3_bucket = S3Bucket(BUCKET_NAME)
        self.client = boto3.client('s3')
        self.text = 'hello\n'
        self.data = self.text.encode('utf-8')

    def test_upload(self):
        with NamedTemporaryFile(delete=True, suffix='.txt') as tmp:
            with open(tmp.name, 'w', encoding='UTF-8') as f:
                f.write(self.text)
            self.s3_bucket.upload(BUCKET_KEY, source_uri=tmp.name)

        bucket_obj = self.client.get_object(Bucket=BUCKET_NAME, Key=BUCKET_KEY)

        expected = self.data
        result = bucket_obj['Body'].read()

        self.assertEqual(expected, result)

```

**Comment by spulec** [comment] 2016-07-10 01:25
I think this is a duplicate of https://github.com/spulec/moto/issues/610, but feel free to reopen if it is not.

**Closed by spulec** 2016-07-10 01:25 UTC
